/**
 * `rivetos gateway` — gateway (embedded den) helpers.
 *
 *   rivetos gateway caps   Allow the gateway to bind :80/:443
 *
 * Bearer mint (`gateway token`) is removed. Off-loopback den requires mesh TLS
 * and a device client cert. See docs/GATEWAY-MTLS.md.
 */

import { execSync } from 'node:child_process'
import { ensureGatewayToken } from '@rivetos/boot'

const CAPS_DROPIN = '/etc/systemd/system/rivetos.service.d/gateway-caps.conf'
const CAPS_CONTENT = `# GENERATED by \`rivetos gateway caps\` (Appendix F G7) — lets the embedded
# gateway bind :80/:443 without root or a reverse proxy. Remove the file and
# daemon-reload to revoke.
[Service]
AmbientCapabilities=CAP_NET_BIND_SERVICE
`

function installCaps(): void {
  const sudo = typeof process.getuid === 'function' && process.getuid() === 0 ? '' : 'sudo '
  try {
    execSync(`${sudo}mkdir -p /etc/systemd/system/rivetos.service.d`, { stdio: 'pipe' })
    execSync(`${sudo}tee ${CAPS_DROPIN} > /dev/null`, {
      input: CAPS_CONTENT,
      stdio: ['pipe', 'pipe', 'pipe'],
    })
    execSync(`${sudo}systemctl daemon-reload`, { stdio: 'pipe' })
    console.log(`✅ ${CAPS_DROPIN} installed — restart rivetos to bind low ports`)
  } catch (err) {
    console.error(`Could not install the drop-in (${(err as Error).message}). Manually:`)
    console.error(`  sudo mkdir -p /etc/systemd/system/rivetos.service.d`)
    console.error(`  sudo tee ${CAPS_DROPIN} <<'EOF'\n${CAPS_CONTENT}EOF`)
    console.error('  sudo systemctl daemon-reload && sudo systemctl restart rivetos')
    process.exitCode = 1
  }
}

export function runGateway(args: string[]): void {
  const sub = args[0]

  if (sub === 'caps') {
    installCaps()
    return
  }

  if (sub === 'token') {
    try {
      ensureGatewayToken()
    } catch (err) {
      console.error(err instanceof Error ? err.message : String(err))
      process.exitCode = 1
    }
    return
  }

  console.log('Usage: rivetos gateway caps')
  if (sub) process.exitCode = 1
}

export default function gateway(): void {
  runGateway(process.argv.slice(3))
}
