/**
 * `rivetos gateway` — gateway (embedded den) helpers.
 *
 *   rivetos gateway token           print the per-node gateway token
 *   rivetos gateway token --rotate  mint a new token (old clients 401 until
 *                                   they pick up the new one)
 *
 * The token lives at ~/.rivetos/gateway.token (0600). It is only consulted
 * when the gateway binds a non-loopback host without an explicit den.token
 * in config — loopback binds run tokenless (private-LAN posture).
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { randomBytes } from 'node:crypto'
import { execSync } from 'node:child_process'

const TOKEN_FILE = join(homedir(), '.rivetos', 'gateway.token')

const CAPS_DROPIN = '/etc/systemd/system/rivetos.service.d/gateway-caps.conf'
const CAPS_CONTENT = `# GENERATED by \`rivetos gateway caps\` (Appendix F G7) — lets the embedded
# gateway bind :80/:443 without root or a reverse proxy. Remove the file and
# daemon-reload to revoke.
[Service]
AmbientCapabilities=CAP_NET_BIND_SERVICE
`

function installCaps(): void {
  const sudo = typeof process.getuid === 'function' && process.getuid() === 0 ? '' : 'sudo '
  try {
    execSync(`${sudo}mkdir -p /etc/systemd/system/rivetos.service.d`, { stdio: 'pipe' })
    execSync(`${sudo}tee ${CAPS_DROPIN} > /dev/null`, {
      input: CAPS_CONTENT,
      stdio: ['pipe', 'pipe', 'pipe'],
    })
    execSync(`${sudo}systemctl daemon-reload`, { stdio: 'pipe' })
    console.log(`✅ ${CAPS_DROPIN} installed — restart rivetos to bind low ports`)
  } catch (err) {
    console.error(`Could not install the drop-in (${(err as Error).message}). Manually:`)
    console.error(`  sudo mkdir -p /etc/systemd/system/rivetos.service.d`)
    console.error(`  sudo tee ${CAPS_DROPIN} <<'EOF'\n${CAPS_CONTENT}EOF`)
    console.error('  sudo systemctl daemon-reload && sudo systemctl restart rivetos')
    process.exitCode = 1
  }
}

export default function gateway(): void {
  const args = process.argv.slice(3)
  const sub = args[0]

  if (sub === 'caps') {
    installCaps()
    return
  }

  if (sub !== 'token') {
    console.log('Usage: rivetos gateway token [--rotate] | rivetos gateway caps')
    process.exitCode = sub ? 1 : 0
    return
  }

  const rotate = args.includes('--rotate')
  if (!rotate && existsSync(TOKEN_FILE)) {
    const token = readFileSync(TOKEN_FILE, 'utf8').trim()
    if (token) {
      console.log(token)
      return
    }
  }

  mkdirSync(join(homedir(), '.rivetos'), { recursive: true })
  const token = randomBytes(24).toString('base64url')
  writeFileSync(TOKEN_FILE, token + '\n', { mode: 0o600 })
  if (rotate) {
    console.error('rotated — restart rivetos so the gateway picks up the new token')
  }
  console.log(token)
}
