/**
 * Transport-agnostic mesh enroll/renew/sync core (plan D8).
 *
 * Unpack, layout, config-snippet merge, and cert-expiry math live here.
 * The SSH (or future HTTPS+token) hop is a single function in `commands/mesh.ts`
 * that returns stdout bytes; nothing in this module talks to the network.
 */

import { copyFile, mkdir, readFile, rename, writeFile, chmod } from 'node:fs/promises'
import { hostname, networkInterfaces } from 'node:os'
import { dirname, join } from 'node:path'
import { randomBytes, X509Certificate } from 'node:crypto'
import { gunzipSync, gzipSync } from 'node:zlib'
import { sharedPath } from '@rivetos/types'
import { parse as parseYaml, stringify as toYaml } from 'yaml'
import { assertRecordMeshFile } from './mesh-file.js'
import { assertSafeArg, isSafeArg, quoteShellArg } from './ssh.js'

export const ENROLL_SNIPPET_MARKER = '# Generated by rivethub-hub enroll'
export const DEFAULT_HUB_CMD = 'rivethub-hub'
export const CERT_EXPIRY_WARN_DAYS = 30
export const DAY_MS = 24 * 60 * 60 * 1000

const TAR_BLOCK = 512
/** Hard cap on gunzip output. A tiny gzip from a malicious hub must not OOM the CLI. */
export const MAX_TAR_DECODED_BYTES = 32 * 1024 * 1024
/** Per-member cap, checked from the header `size` before copying bytes. */
export const MAX_TAR_MEMBER_BYTES = 8 * 1024 * 1024

export interface TarLimits {
  maxDecodedBytes?: number
  maxMemberBytes?: number
}

export type MeshHubErrorCode =
  'ssh-auth' | 'ssh-failed' | 'helper-missing' | 'malformed-tarball' | 'malformed-mesh' | 'usage'

export class MeshHubError extends Error {
  readonly code: MeshHubErrorCode
  constructor(code: MeshHubErrorCode, message: string) {
    super(message)
    this.name = 'MeshHubError'
    this.code = code
  }
}

export interface UserHost {
  user: string
  host: string
  target: string
}

export interface EnrollArgs {
  user: string
  host: string
  target: string
  name: string
  advertise: string | undefined
  hubCmd: string
}

export interface SyncArgs {
  user: string
  host: string
  target: string
  hubCmd: string
}

export interface RenewArgs {
  user: string
  host: string
  target: string
  name: string
  hubCmd: string
}

export interface UnpackedEnroll {
  name: string
  cert: Buffer
  key: Buffer
  caChain: Buffer
  meshJson: string
  snippet: string
}

export type CertExpiryKind = 'ok' | 'warn' | 'expired'

export interface LeafCertExpiryResult {
  status: 'pass' | 'warn' | 'fail'
  message: string
  detail?: string
}

// ---------------------------------------------------------------------------
// node name / user@host
// ---------------------------------------------------------------------------

/** Same charset as rivethub-hub: DNS-label, [a-z0-9-], max 63, no leading/trailing hyphen. */
export function validateNodeName(name: string): boolean {
  return name.length > 0 && name.length <= 63 && /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/.test(name)
}

export function parseUserHost(spec: string): UserHost {
  const at = spec.lastIndexOf('@')
  if (at <= 0 || at === spec.length - 1) {
    throw new MeshHubError('usage', `expected user@host, got "${spec}"`)
  }
  const user = spec.slice(0, at)
  const host = spec.slice(at + 1)
  if (!isSafeArg(user) || !isSafeArg(host)) {
    throw new MeshHubError('usage', `refusing unsafe user@host "${spec}"`)
  }
  return { user, host, target: `${user}@${host}` }
}

function requireFlagValue(args: string[], i: number, flag: string): string {
  const value = args[i + 1]
  if (!value || value.startsWith('--')) {
    throw new MeshHubError('usage', `${flag} requires a value`)
  }
  return value
}

function parseHubFlags(args: string[]): {
  positionals: string[]
  name: string | undefined
  advertise: string | undefined
  hubCmd: string
} {
  let name: string | undefined
  let advertise: string | undefined
  let hubCmd = DEFAULT_HUB_CMD
  const positionals: string[] = []
  for (let i = 0; i < args.length; i++) {
    const a = args[i]
    if (a === '--name') {
      name = requireFlagValue(args, i, '--name')
      i++
      continue
    }
    if (a === '--advertise') {
      advertise = requireFlagValue(args, i, '--advertise')
      i++
      continue
    }
    if (a === '--hub-cmd') {
      hubCmd = requireFlagValue(args, i, '--hub-cmd')
      i++
      continue
    }
    if (a === '--json' || a === '--manual') continue
    if (a === '--timeout' || a === '--port' || a === '--ssh-user') {
      i++
      continue
    }
    if (a.startsWith('--')) {
      throw new MeshHubError('usage', `Unknown option: ${a}`)
    }
    positionals.push(a)
  }
  if (!isSafeArg(hubCmd)) {
    throw new MeshHubError('usage', `refusing unsafe --hub-cmd "${hubCmd}"`)
  }
  if (advertise !== undefined && !isSafeArg(advertise)) {
    throw new MeshHubError('usage', `refusing unsafe --advertise "${advertise}"`)
  }
  return { positionals, name, advertise, hubCmd }
}

function requireName(name: string | undefined, usage: string): string {
  if (!name) {
    throw new MeshHubError('usage', `--name <node> is required\n  ${usage}`)
  }
  if (!validateNodeName(name)) {
    throw new MeshHubError(
      'usage',
      `invalid node name "${name}" — must match [a-z0-9]([a-z0-9-]*[a-z0-9])? (max 63)`,
    )
  }
  return name
}

const ENROLL_USAGE =
  'Usage: rivetos mesh enroll <user@host> --name <node> [--advertise <host|ip>] [--hub-cmd rivethub-hub]'
const SYNC_USAGE = 'Usage: rivetos mesh sync <user@host> [--hub-cmd rivethub-hub]'
const RENEW_USAGE = 'Usage: rivetos mesh renew <user@host> --name <node> [--hub-cmd rivethub-hub]'

export function parseEnrollArgs(args: string[]): EnrollArgs {
  const parsed = parseHubFlags(args)
  const target = parsed.positionals[0]
  if (!target) throw new MeshHubError('usage', ENROLL_USAGE)
  const uh = parseUserHost(target)
  return {
    ...uh,
    name: requireName(parsed.name, ENROLL_USAGE),
    advertise: parsed.advertise,
    hubCmd: parsed.hubCmd,
  }
}

export function parseSyncArgs(args: string[]): SyncArgs {
  const parsed = parseHubFlags(args)
  const target = parsed.positionals[0]
  if (!target) throw new MeshHubError('usage', SYNC_USAGE)
  return { ...parseUserHost(target), hubCmd: parsed.hubCmd }
}

export function parseRenewArgs(args: string[]): RenewArgs {
  const parsed = parseHubFlags(args)
  const target = parsed.positionals[0]
  if (!target) throw new MeshHubError('usage', RENEW_USAGE)
  return {
    ...parseUserHost(target),
    name: requireName(parsed.name, RENEW_USAGE),
    hubCmd: parsed.hubCmd,
  }
}

/**
 * Build the remote hub argv. PATH prefix matches node.sh: non-login ssh often
 * drops /usr/local/bin (where datahub.sh installs rivethub-hub).
 *
 * Injection defense is layered: `isSafeArg` rejects `; $ \` ' " whitespace` and
 * allows `:` (IPv6) and `@` (see `ssh.test.ts`); `quoteShellArg` then
 * single-quotes and POSIX-escapes embedded quotes. The ssh hop passes this
 * string as one argv element, not through a local shell.
 */
export function hubRemoteCommand(
  hubCmd: string,
  sub: 'enroll' | 'renew' | 'mesh-export',
  name?: string,
  advertise?: string,
): string {
  assertSafeArg(hubCmd, '--hub-cmd')
  const parts = ['PATH=/usr/local/bin:/usr/bin:/bin:$PATH', quoteShellArg(hubCmd), sub]
  if (name !== undefined) parts.push(quoteShellArg(name))
  if (advertise !== undefined) parts.push(quoteShellArg(advertise))
  return parts.join(' ')
}

/**
 * Address other nodes should use to reach this host when --advertise is omitted.
 * Prefer a non-localhost hostname; otherwise the first non-internal IPv4.
 *
 * `hostName` / `ifaces` are injectable so tests can cover every fallback without
 * mocking `node:os` (named imports are not spyable under ESM).
 */
export function defaultAdvertiseHost(
  hostName: string = hostname(),
  ifaces: ReturnType<typeof networkInterfaces> = networkInterfaces(),
): string {
  if (
    hostName &&
    hostName !== 'localhost' &&
    hostName !== 'localhost.localdomain' &&
    isSafeArg(hostName)
  ) {
    return hostName
  }
  for (const list of Object.values(ifaces)) {
    for (const iface of list ?? []) {
      if (iface.family === 'IPv4' && !iface.internal && isSafeArg(iface.address)) {
        return iface.address
      }
    }
  }
  return '127.0.0.1'
}

// ---------------------------------------------------------------------------
// gzip+ustar (no extra deps — node:zlib is built in)
// ---------------------------------------------------------------------------

function readTarString(block: Buffer, offset: number, length: number): string {
  const slice = block.subarray(offset, offset + length)
  const end = slice.indexOf(0)
  return slice
    .subarray(0, end === -1 ? length : end)
    .toString('utf-8')
    .trim()
}

function parseOctal(buf: Buffer): number {
  const raw = buf.toString('ascii').replace(/\0/g, ' ').trim()
  if (!raw) return 0
  const n = Number.parseInt(raw, 8)
  return Number.isFinite(n) ? n : 0
}

function isZeroBlock(block: Buffer): boolean {
  for (let i = 0; i < block.length; i++) {
    if (block[i] !== 0) return false
  }
  return true
}

function safeMemberName(name: string): string {
  const n = name.replace(/^\.\//, '')
  if (!n || n.includes('..') || n.includes('/') || n.includes('\\')) {
    throw new MeshHubError('malformed-tarball', `enroll tarball has unsafe path: ${name}`)
  }
  return n
}

/** POSIX/GNU unsigned checksum: treat chksum bytes (148–155) as spaces. */
function tarUnsignedChecksum(header: Buffer): number {
  let sum = 0
  for (let i = 0; i < TAR_BLOCK; i++) {
    sum += i >= 148 && i < 156 ? 0x20 : (header[i] ?? 0)
  }
  return sum
}

function isInflateTooLarge(err: unknown): boolean {
  if (!(err instanceof Error)) return false
  const code = (err as NodeJS.ErrnoException).code
  return (
    code === 'ERR_BUFFER_TOO_LARGE' ||
    err.name === 'RangeError' ||
    /too large|exceed/i.test(err.message)
  )
}

/** Unpack a gzip-compressed ustar archive into basename → bytes. */
export function extractTarGz(buf: Buffer, limits: TarLimits = {}): Map<string, Buffer> {
  const maxDecoded = limits.maxDecodedBytes ?? MAX_TAR_DECODED_BYTES
  const maxMember = limits.maxMemberBytes ?? MAX_TAR_MEMBER_BYTES
  if (buf.length < 2 || buf[0] !== 0x1f || buf[1] !== 0x8b) {
    throw new MeshHubError('malformed-tarball', 'enroll tarball is not gzip-compressed')
  }
  let tar: Buffer
  try {
    tar = gunzipSync(buf, { maxOutputLength: maxDecoded })
  } catch (err) {
    if (isInflateTooLarge(err)) {
      throw new MeshHubError(
        'malformed-tarball',
        `enroll tarball exceeds ${String(maxDecoded)} bytes decompressed`,
      )
    }
    throw new MeshHubError('malformed-tarball', 'enroll tarball failed to decompress')
  }
  const files = new Map<string, Buffer>()
  let offset = 0
  while (offset + TAR_BLOCK <= tar.length) {
    const header = tar.subarray(offset, offset + TAR_BLOCK)
    if (isZeroBlock(header)) break
    const storedSum = parseOctal(header.subarray(148, 156))
    if (storedSum !== tarUnsignedChecksum(header)) {
      throw new MeshHubError(
        'malformed-tarball',
        'enroll tarball has a corrupt header (checksum mismatch)',
      )
    }
    const name = readTarString(header, 0, 100)
    const prefix = readTarString(header, 345, 155)
    const size = parseOctal(header.subarray(124, 136))
    const typeflag = String.fromCharCode(header[156] ?? 0)
    offset += TAR_BLOCK
    if (size > maxMember) {
      throw new MeshHubError(
        'malformed-tarball',
        `enroll tarball member exceeds ${String(maxMember)} bytes`,
      )
    }
    if (offset + size > tar.length) {
      throw new MeshHubError('malformed-tarball', 'enroll tarball is truncated')
    }
    const padded = Math.ceil(size / TAR_BLOCK) * TAR_BLOCK
    const data = tar.subarray(offset, offset + size)
    offset += padded
    if (!name && !prefix) continue
    const full = prefix ? `${prefix}/${name}` : name
    // Regular files only. Skip dirs / pax / gnu longname.
    if (typeflag === '0' || typeflag === '\0' || typeflag === '') {
      files.set(safeMemberName(full), Buffer.from(data))
    }
  }
  return files
}

function writeOctal(buf: Buffer, offset: number, value: number, length: number): void {
  const s = value.toString(8).padStart(length - 1, '0')
  buf.write(s, offset, 'ascii')
  buf[offset + length - 1] = 0
}

/**
 * Pack a flat basename→bytes map into a gzip ustar. Used by tests to build
 * fixture tarballs that match the hub's `tar -czf` contract.
 */
export function packTarGz(files: Record<string, Buffer | string>): Buffer {
  const parts: Buffer[] = []
  for (const [name, content] of Object.entries(files)) {
    const data = typeof content === 'string' ? Buffer.from(content, 'utf-8') : content
    const nameBuf = Buffer.from(name, 'utf-8')
    if (nameBuf.length > 99) {
      throw new Error(`tar member name too long: ${name}`)
    }
    const header = Buffer.alloc(TAR_BLOCK, 0)
    nameBuf.copy(header, 0)
    writeOctal(header, 100, 0o644, 8)
    writeOctal(header, 108, 0, 8)
    writeOctal(header, 116, 0, 8)
    writeOctal(header, 124, data.length, 12)
    writeOctal(header, 136, Math.floor(Date.now() / 1000), 12)
    header.write('        ', 148, 'ascii')
    header[156] = 0x30 // '0'
    header.write('ustar\0', 257, 'ascii')
    header.write('00', 263, 'ascii')
    let sum = 0
    for (let i = 0; i < TAR_BLOCK; i++) sum += header[i]
    const chk = sum.toString(8).padStart(6, '0')
    header.write(`${chk}\0 `, 148, 'ascii')
    parts.push(header)
    parts.push(data)
    const rem = data.length % TAR_BLOCK
    if (rem !== 0) parts.push(Buffer.alloc(TAR_BLOCK - rem))
  }
  parts.push(Buffer.alloc(TAR_BLOCK * 2))
  return gzipSync(Buffer.concat(parts))
}

const CANONICAL_B64 = /^[A-Za-z0-9+/]+={0,2}$/

export function decodeEnrollB64(stdout: string): Buffer {
  const cleaned = stdout.replace(/\s+/g, '')
  if (!cleaned) {
    throw new MeshHubError(
      'malformed-tarball',
      'enroll produced an empty tarball (remote diagnostics are on stderr)',
    )
  }
  // Node's base64 decoder skips invalid chars, so `Buffer.from(s, 'base64').length === 0`
  // almost never fires for nonempty garbage. Require a canonical alphabet so an rc
  // echo / MOTD mixed into stdout is a clear "not valid base64", not "not gzip".
  // A hub begin/end marker would be a wire-protocol change; charset is the local guard.
  if (cleaned.length % 4 !== 0 || !CANONICAL_B64.test(cleaned)) {
    throw new MeshHubError(
      'malformed-tarball',
      'enroll stdout is not valid base64 (unexpected output mixed with the tarball?)',
    )
  }
  const buf = Buffer.from(cleaned, 'base64')
  if (buf.length === 0) {
    throw new MeshHubError('malformed-tarball', 'enroll tarball was not valid base64')
  }
  return buf
}

export function parseEnrollTarball(b64Stdout: string, name: string): UnpackedEnroll {
  const gz = decodeEnrollB64(b64Stdout)
  const files = extractTarGz(gz)
  const get = (filename: string): Buffer => {
    const buf = files.get(filename)
    if (!buf) {
      throw new MeshHubError('malformed-tarball', `enroll tarball missing ${filename}`)
    }
    return buf
  }
  const meshJson = get('mesh.json').toString('utf-8')
  try {
    meshNodeCount(meshJson, 'enroll-mesh.json')
  } catch {
    throw new MeshHubError(
      'malformed-tarball',
      'enroll tarball mesh.json is not a valid Record-format mesh file',
    )
  }
  return {
    name,
    cert: get(`${name}.crt`),
    key: get(`${name}.key`),
    caChain: get('ca-chain.pem'),
    meshJson,
    snippet: get('node-config-snippet.yaml').toString('utf-8'),
  }
}

export async function atomicWriteFile(
  path: string,
  data: string | Buffer,
  mode = 0o600,
): Promise<void> {
  const tmp = `${path}.tmp.${String(process.pid)}.${randomBytes(8).toString('hex')}`
  await writeFile(tmp, data, { mode })
  await rename(tmp, path)
}

/**
 * Place leaf + chain + mesh.json where mtls.ts / loadMeshFile expect them:
 *   $RIVETOS_SHARED_DIR/rivet-ca/issued/<name>.{crt,key}
 *   $RIVETOS_SHARED_DIR/rivet-ca/intermediate/{ca-chain,chain}.pem
 *   $RIVETOS_SHARED_DIR/mesh.json
 */
export async function writeEnrollLayout(unpacked: UnpackedEnroll): Promise<void> {
  const issued = sharedPath('rivet-ca', 'issued')
  const intermediate = sharedPath('rivet-ca', 'intermediate')
  // Create issued/ at 0700 — do not mkdir 0755 then chmod; that window is
  // visible on the group-shared/NFS tree. chmod after covers an already-existing dir.
  await mkdir(issued, { recursive: true, mode: 0o700 })
  await mkdir(intermediate, { recursive: true })
  await chmod(issued, 0o700).catch(() => undefined)
  const certPath = join(issued, `${unpacked.name}.crt`)
  const keyPath = join(issued, `${unpacked.name}.key`)
  await writeFile(certPath, unpacked.cert)
  // mode on create; chmod after because writeFile's mode is ignored on re-enroll.
  await writeFile(keyPath, unpacked.key, { mode: 0o600 })
  await chmod(keyPath, 0o600)
  await writeFile(join(intermediate, 'ca-chain.pem'), unpacked.caChain)
  await writeFile(join(intermediate, 'chain.pem'), unpacked.caChain)
  await atomicWriteFile(sharedPath('mesh.json'), unpacked.meshJson)
}

export function configPath(): string {
  return join(process.env.HOME ?? '.', '.rivetos', 'config.yaml')
}

/**
 * Canonical `mesh:` mapping for both `rivetos mesh enroll` (via
 * {@link formatEnrollSnippet} → {@link mergeConfigFile}) and `rivetos init`
 * (`generateConfig`). Hub snippet keys are kept; `enabled`, `node_name`, and
 * `tls` are filled so the boot validator accepts the result even when the
 * snippet omits them. `advertise_host` is written only when the caller passes
 * an explicit advertise (or the snippet already has one) — auto-detected
 * enroll hosts are not pinned, so boot can re-detect via
 * `resolveAdvertiseHost`.
 */
export function meshSectionFromEnroll(
  unpacked: Pick<UnpackedEnroll, 'name' | 'snippet'>,
  advertise?: string,
): Record<string, unknown> {
  let fromSnippet: Record<string, unknown> = {}
  try {
    const parsed: unknown = parseYaml(unpacked.snippet)
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
      const mesh = (parsed as Record<string, unknown>).mesh
      if (mesh && typeof mesh === 'object' && !Array.isArray(mesh)) {
        fromSnippet = { ...(mesh as Record<string, unknown>) }
      }
    }
  } catch {
    // Snippet is advisory; identity below is enough for a valid mesh section.
  }
  const section: Record<string, unknown> = {
    ...fromSnippet,
    enabled: true,
    node_name: unpacked.name,
    tls: fromSnippet.tls ?? true,
  }
  if (advertise) {
    section.advertise_host = advertise
  } else if (typeof fromSnippet.advertise_host === 'string' && fromSnippet.advertise_host.trim()) {
    section.advertise_host = fromSnippet.advertise_host
  }
  return section
}

/** Marker-prefixed YAML document {@link mergeConfigFile} appends. */
export function formatEnrollSnippet(
  unpacked: Pick<UnpackedEnroll, 'name' | 'snippet'>,
  advertise?: string,
): string {
  const section = meshSectionFromEnroll(unpacked, advertise)
  const body = toYaml(
    { mesh: section },
    { lineWidth: 120, defaultKeyType: 'PLAIN', defaultStringType: 'PLAIN' },
  )
  const yaml = body.endsWith('\n') ? body : `${body}\n`
  return `${ENROLL_SNIPPET_MARKER}. Merge into the node's rivet.config.yaml.\n${yaml}`
}

function snippetNodeName(text: string): string | undefined {
  const m = text.match(/^\s*node_name:\s*["']?([a-z0-9](?:[a-z0-9-]*[a-z0-9])?)["']?\s*$/m)
  return m?.[1]
}

export function mergeConfigSnippet(
  existing: string | null,
  snippet: string,
): { next: string; changed: boolean; warning?: string } {
  const body = snippet.endsWith('\n') ? snippet : `${snippet}\n`
  // Marker-gated: once the enroll snippet is present we never rewrite it
  // (re-enroll refreshes certs + mesh.json only). Content-blind no-op besides
  // a node_name mismatch warning — edit or delete the marker block to re-merge.
  if (existing && existing.includes(ENROLL_SNIPPET_MARKER)) {
    const existingName = snippetNodeName(existing)
    const incomingName = snippetNodeName(snippet)
    const warning =
      existingName && incomingName && existingName !== incomingName
        ? `existing enroll snippet has node_name "${existingName}"; incoming "${incomingName}" was not applied (marker-gated no-op)`
        : undefined
    return { next: existing, changed: false, warning }
  }
  if (!existing) {
    return { next: body, changed: true }
  }
  const sep = existing.endsWith('\n') ? '' : '\n'
  return { next: existing + sep + body, changed: true }
}

export type MergeConfigResult = 'appended' | 'created' | 'unchanged'

export async function mergeConfigFile(
  snippet: string,
  path = configPath(),
): Promise<{ result: MergeConfigResult; warning?: string }> {
  let existing: string | null
  try {
    existing = await readFile(path, 'utf-8')
  } catch {
    existing = null
  }
  const { next, changed, warning } = mergeConfigSnippet(existing, snippet)
  if (!changed) return { result: 'unchanged', warning }
  await mkdir(dirname(path), { recursive: true })
  if (existing !== null) {
    await copyFile(path, `${path}.bak`)
  }
  // 0o600 is intentional: config.yaml holds enroll material. Atomic temp+rename
  // matches mesh.json so a crash mid-write cannot truncate the live file.
  await atomicWriteFile(path, next, 0o600)
  await chmod(path, 0o600)
  return { result: existing === null ? 'created' : 'appended', warning }
}

export function meshNodeCount(raw: string, path = 'mesh.json'): number {
  const parsed: unknown = JSON.parse(raw)
  const mesh = assertRecordMeshFile(parsed, path)
  return Object.keys(mesh.nodes).length
}

function isEnoent(err: unknown): boolean {
  return typeof err === 'object' && err !== null && (err as { code?: string }).code === 'ENOENT'
}

export async function readLocalMeshNodeCount(): Promise<number> {
  const path = sharedPath('mesh.json')
  let raw: string
  try {
    raw = await readFile(path, 'utf-8')
  } catch (err) {
    if (isEnoent(err)) return 0
    throw err
  }
  try {
    return meshNodeCount(raw, path)
  } catch {
    throw new MeshHubError(
      'malformed-mesh',
      `local mesh.json at ${path} is not a valid Record-format mesh file`,
    )
  }
}

// ---------------------------------------------------------------------------
// cert expiry (node:crypto X509Certificate — no openssl)
// ---------------------------------------------------------------------------

export function parseCertNotAfter(pem: string): Date {
  const cert = new X509Certificate(pem)
  // X509Certificate.validTo is OpenSSL's UTC string ("Mon DD HH:MM:SS YYYY GMT").
  // A missing GMT/Z would be parsed as local time and shift the 30-day judgment
  // by the TZ offset. Force UTC when the suffix is absent.
  let raw = cert.validTo.trim()
  if (!/(?:GMT|UTC|Z)$/i.test(raw)) {
    raw = `${raw} GMT`
  }
  const parsed = new Date(raw)
  if (Number.isNaN(parsed.getTime())) {
    throw new Error(`cannot parse certificate notAfter "${cert.validTo}"`)
  }
  return parsed
}

export function classifyCertExpiry(
  notAfter: Date,
  now: Date,
  warnDays = CERT_EXPIRY_WARN_DAYS,
): CertExpiryKind {
  const remaining = notAfter.getTime() - now.getTime()
  if (remaining <= 0) return 'expired'
  if (remaining <= warnDays * DAY_MS) return 'warn'
  return 'ok'
}

export function renewCommand(hubTarget: string, nodeName: string): string {
  return `rivetos mesh renew ${hubTarget} --name ${nodeName}`
}

export function leafCertExpiryCheck(opts: {
  certPem: string
  nodeName: string
  hubTarget: string
  now?: Date
}): LeafCertExpiryResult {
  const now = opts.now ?? new Date()
  let notAfter: Date
  try {
    notAfter = parseCertNotAfter(opts.certPem)
  } catch {
    return {
      status: 'warn',
      message: `Leaf cert for ${opts.nodeName}: unreadable or invalid`,
    }
  }
  const kind = classifyCertExpiry(notAfter, now)
  const iso = notAfter.toISOString()
  const cmd = renewCommand(opts.hubTarget, opts.nodeName)
  if (kind === 'expired') {
    return {
      status: 'fail',
      message: `Leaf cert for ${opts.nodeName} expired (${iso})`,
      detail: `Run: ${cmd}`,
    }
  }
  if (kind === 'warn') {
    const days = Math.max(1, Math.ceil((notAfter.getTime() - now.getTime()) / DAY_MS))
    return {
      status: 'warn',
      message: `Leaf cert for ${opts.nodeName} expires in ${String(days)} day(s) (notAfter ${iso})`,
      detail: `Run: ${cmd}`,
    }
  }
  return {
    status: 'pass',
    message: `Leaf cert for ${opts.nodeName}: valid until ${iso}`,
  }
}

/** Placeholder hub target when config has no seed_host. Matches the task's user@datahub form. */
export const DEFAULT_RENEW_HUB_TARGET = 'user@datahub'

export function renewHubTargetFromSeed(seedHost: string | undefined): string {
  if (seedHost && isSafeArg(seedHost)) return `rivet@${seedHost}`
  return DEFAULT_RENEW_HUB_TARGET
}

export { sharedPath }
