#!/usr/bin/env bats
# Pure-logic tests for install/node.sh. ssh/git/npm/systemctl are fakes in
# PATH. No real datahub, docker, or CA. Requires bats; tests avoid
# `run --separate-stderr`. Reviewer: chmod +x is not required (invoked via bash).

NODE_SH="${BATS_TEST_DIRNAME}/../install/node.sh"
REPO="$(cd "${BATS_TEST_DIRNAME}/.." && pwd)"

setup() {
  TEST_TMP="$(mktemp -d)"
  export TEST_TMP
  export RIVETHUB_TEST=1
  export RIVETHUB_ROOT="${TEST_TMP}/hub"
  export RIVETHUB_DISTRO_DIR="${REPO}"
  export RIVETHUB_SYSTEMD_DIR="${TEST_TMP}/systemd"
  export RIVETOS_INSTALL_ROOT="${TEST_TMP}/opt/rivetos"
  export RIVETOS_SHARED_DIR="${TEST_TMP}/hub/shared"
  export RIVETOS_HOME="${TEST_TMP}/home/rivet"
  export RIVETHUB_OS_RELEASE="${BATS_TEST_DIRNAME}/fixtures/os-release-debian"
  export RIVETHUB_ADVERTISE_HOST="192.0.2.11"

  mkdir -p "${TEST_TMP}/bin" "${RIVETHUB_SYSTEMD_DIR}" "${RIVETOS_HOME}" \
    "${RIVETOS_SHARED_DIR}" "${RIVETOS_INSTALL_ROOT}"
  export PATH="${TEST_TMP}/bin:${PATH}"
}

teardown() {
  rm -rf "${TEST_TMP}"
}

# Source node.sh in a subshell and run a function (does not invoke main).
src() {
  bash -c '
    source "$1"
    shift
    "$@"
  ' bash "${NODE_SH}" "$@"
}

parse_print() {
  bash -c '
    source "$1"
    shift
    parse_args "$@"
    printf "docker=%s hub=%s name=%s host=%s answers=%s help=%s force=%s yes=%s\n" \
      "${FLAG_DOCKER}" "${HUB_TARGET}" "${NODE_NAME}" "${ADVERTISE_HOST}" \
      "${ANSWERS_FILE}" "${FLAG_HELP}" "${FLAG_FORCE}" "${FLAG_YES}"
  ' bash "${NODE_SH}" "$@"
}

make_bundle() {
  local name="${1:-node-a}"
  local dir="${TEST_TMP}/bundle"
  mkdir -p "${dir}"
  # bash printf treats a format starting with - as options (SC: -- ends them).
  printf -- '-----BEGIN CERTIFICATE-----\nCERT\n-----END CERTIFICATE-----\n' >"${dir}/${name}.crt"
  printf -- '-----BEGIN PRIVATE KEY-----\nKEYMATERIAL-do-not-print\n-----END PRIVATE KEY-----\n' >"${dir}/${name}.key"
  printf -- '-----BEGIN CERTIFICATE-----\nCHAIN\n-----END CERTIFICATE-----\n' >"${dir}/ca-chain.pem"
  cat >"${dir}/mesh.json" <<EOF
{
  "version": 1,
  "nodes": {
    "${name}": {
      "id": "${name}",
      "name": "${name}",
      "host": "192.0.2.11",
      "port": 3000,
      "status": "offline",
      "role": "agent"
    }
  },
  "updatedAt": 0
}
EOF
  cat >"${dir}/node-config-snippet.yaml" <<EOF
# Generated by rivethub-hub enroll. Merge into the node's rivet.config.yaml.
# storage_dir is this node's local RIVETOS_SHARED_DIR (distro default shown).
mesh:
  enabled: true
  node_name: "${name}"
  tls: true
  agent_channel_port: 3000
  storage_dir: "/var/lib/rivethub/shared"
  discovery:
    mode: seed
    seed_host: "192.0.2.10"
    seed_port: 3000
EOF
  tar -C "${dir}" -czf "${TEST_TMP}/bundle.tgz" \
    "${name}.crt" "${name}.key" ca-chain.pem mesh.json node-config-snippet.yaml
  base64 -w0 <"${TEST_TMP}/bundle.tgz" >"${TEST_TMP}/bundle.b64"
  printf '\n' >>"${TEST_TMP}/bundle.b64"
}

install_ssh_stub() {
  cat >"${TEST_TMP}/bin/ssh" <<EOF
#!/usr/bin/env bash
set -euo pipefail
echo "ssh \$*" >>"${TEST_TMP}/ssh.log"
remote="\${@: -1}"
if [[ "\${remote}" == "true" ]]; then
  if [[ -f "${TEST_TMP}/ssh-deny" ]]; then
    echo "Permission denied (publickey)." >&2
    exit 255
  fi
  if [[ -f "${TEST_TMP}/ssh-down" ]]; then
    echo "Connection timed out" >&2
    exit 1
  fi
  exit 0
fi
if [[ "\${remote}" == *enroll* ]]; then
  if [[ -f "${TEST_TMP}/ssh-enroll-fail" ]]; then
    echo "rivethub-hub: enroll failed" >&2
    exit 1
  fi
  if [[ -f "${TEST_TMP}/ssh-enroll-empty" ]]; then
    exit 0
  fi
  cat "${TEST_TMP}/bundle.b64"
  exit 0
fi
if [[ "\${remote}" == *authorized_keys* ]]; then
  cat >>"${TEST_TMP}/hub-authorized-keys"
  exit 0
fi
echo "ssh stub: unexpected remote: \${remote}" >&2
exit 1
EOF
  chmod +x "${TEST_TMP}/bin/ssh"
}

# ---------------------------------------------------------------------------
# argument parsing
# ---------------------------------------------------------------------------

@test "-h prints usage mentioning docker, hub, enroll, and --yes" {
  run bash "${NODE_SH}" -h
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"--docker"* ]]
  [[ "${output}" == *"--hub"* ]]
  [[ "${output}" == *"enroll"* ]]
  [[ "${output}" == *"--yes"* ]]
  [[ "${output}" == *"192.0.2.10"* ]]
  [[ "${output}" == *"rivetos mesh sync"* ]]
}

@test "unknown option is refused" {
  run bash "${NODE_SH}" --not-a-flag
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"unknown option"* ]]
}

@test "unexpected positional is refused" {
  run bash "${NODE_SH}" leftover
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"unexpected argument"* ]]
}

@test "parse_args records --docker --hub --name --advertise-host" {
  out="$(parse_print --docker --hub owner@192.0.2.10 --name node-a --advertise-host 192.0.2.11)"
  [[ "${out}" == *"docker=1"* ]]
  [[ "${out}" == *"hub=owner@192.0.2.10"* ]]
  [[ "${out}" == *"name=node-a"* ]]
  [[ "${out}" == *"host=192.0.2.11"* ]]
}

@test "parse_args defaults are bare-metal empty hub" {
  out="$(parse_print)"
  [[ "${out}" == *"docker=0"* ]]
  [[ "${out}" == *"hub="* ]]
  [[ "${out}" == *"help=0"* ]]
}

@test "--hub=owner@192.0.2.10 equals --hub owner@192.0.2.10" {
  out="$(parse_print --hub=owner@192.0.2.10)"
  [[ "${out}" == *"hub=owner@192.0.2.10"* ]]
}

@test "--hub without a value is refused" {
  run parse_print --hub
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"--hub requires"* ]]
}

@test "invalid --hub is refused" {
  run parse_print --hub 192.0.2.10
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"invalid --hub"* ]]
}

@test "invalid --name is refused" {
  run parse_print --name 'NodeA'
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"invalid --name"* ]]
}

@test "invalid --advertise-host with shell metacharacters is refused" {
  run parse_print --advertise-host 'x:;id'
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"invalid --advertise-host"* ]]
}

@test "bracketed IPv6 --advertise-host is accepted and unbracketed" {
  out="$(parse_print --advertise-host '[::1]')"
  [[ "${out}" == *"host=::1"* ]]
}

@test "--hub user starting with a dash is refused" {
  run parse_print --hub '-x@192.0.2.10'
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"invalid --hub"* ]]
}

@test "--answers-file missing path is refused" {
  run parse_print --answers-file "${TEST_TMP}/no-such-answers"
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"--answers-file"* ]]
}

# ---------------------------------------------------------------------------
# preflight refusals
# ---------------------------------------------------------------------------

@test "preflight_tools refuses when curl is missing" {
  run bash -c '
    export PATH="$1"
    export RIVETHUB_TEST=1
    source "$2"
    init_paths
    FLAG_DOCKER=0
    preflight_tools
  ' bash "${TEST_TMP}/empty-path" "${NODE_SH}"
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"missing required tools"* ]]
}

@test "preflight_os warns (does not block) on a non-Debian ID" {
  run bash -c '
    source "$1"
    export RIVETHUB_OS_RELEASE="$2"
    init_paths
    preflight_os
  ' bash "${NODE_SH}" "${BATS_TEST_DIRNAME}/fixtures/os-release-other"
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"warning"* ]]
  [[ "${output}" == *"Debian 12 / Ubuntu LTS"* ]]
}

@test "preflight_os accepts Debian 12" {
  run src preflight_os
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"Debian GNU/Linux 12"* ]]
  [[ "${output}" != *"warning"* ]]
}

@test "preflight_hub refuses when hub is empty and stdin is not a TTY" {
  run bash -c '
    source "$1"
    init_paths
    HUB_TARGET=""
    preflight_hub
  ' bash "${NODE_SH}"
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"--hub"* ]]
}

# ---------------------------------------------------------------------------
# ssh BatchMode probe branches
# ---------------------------------------------------------------------------

@test "ssh_preflight succeeds when BatchMode probe returns 0" {
  install_ssh_stub
  run bash -c '
    source "$1"
    init_paths
    ssh_preflight owner@192.0.2.10
  ' bash "${NODE_SH}"
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"ssh to owner@192.0.2.10 ok"* ]]
  grep -q "BatchMode=yes" "${TEST_TMP}/ssh.log"
}

@test "ssh_preflight coaches ssh-copy-id on Permission denied" {
  install_ssh_stub
  touch "${TEST_TMP}/ssh-deny"
  run bash -c '
    source "$1"
    init_paths
    ssh_preflight owner@192.0.2.10
  ' bash "${NODE_SH}"
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"ssh-copy-id owner@192.0.2.10"* ]]
  [[ "${output}" == *"Permission denied"* ]]
  [[ "${output}" == *"/root/.ssh"* ]]
}

@test "ssh_preflight cannot-reach branch does not hang and mentions ssh-copy-id" {
  install_ssh_stub
  touch "${TEST_TMP}/ssh-down"
  run bash -c '
    source "$1"
    init_paths
    ssh_preflight owner@192.0.2.10
  ' bash "${NODE_SH}"
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"cannot reach"* ]]
  [[ "${output}" == *"ssh-copy-id"* ]]
}

# ---------------------------------------------------------------------------
# enroll_via_ssh tarball unpack + config merge idempotency
# ---------------------------------------------------------------------------

@test "unpack_enroll_bundle places certs mesh.json and 0600 key" {
  make_bundle node-a
  bash -c '
    source "$1"
    init_paths
    NODE_NAME=node-a
    unpack_enroll_bundle "$2" node-a
  ' bash "${NODE_SH}" "${TEST_TMP}/bundle.b64"
  [ -f "${RIVETOS_SHARED_DIR}/rivet-ca/issued/node-a.crt" ]
  [ -f "${RIVETOS_SHARED_DIR}/rivet-ca/issued/node-a.key" ]
  [ "$(stat -c %a "${RIVETOS_SHARED_DIR}/rivet-ca/issued/node-a.key")" = "600" ]
  [ -f "${RIVETOS_SHARED_DIR}/rivet-ca/intermediate/ca-chain.pem" ]
  [ -f "${RIVETOS_SHARED_DIR}/rivet-ca/intermediate/chain.pem" ]
  [ -f "${RIVETOS_SHARED_DIR}/mesh.json" ]
  [ -f "${RIVETOS_HOME}/.rivetos/config.yaml" ]
  grep -q 'node_name: "node-a"' "${RIVETOS_HOME}/.rivetos/config.yaml"
  grep -q 'agent_channel_port: 3000' "${RIVETOS_HOME}/.rivetos/config.yaml"
  grep -q "storage_dir: \"${RIVETOS_SHARED_DIR}\"" "${RIVETOS_HOME}/.rivetos/config.yaml"
  python3 - "${RIVETOS_SHARED_DIR}/mesh.json" <<'PY'
import json, sys
data = json.load(open(sys.argv[1], encoding="utf-8"))
assert data["version"] == 1
assert "node-a" in data["nodes"]
assert data["nodes"]["node-a"]["host"] == "192.0.2.11"
assert data["nodes"]["node-a"]["port"] == 3000
PY
}

@test "merge_config_snippet is idempotent (re-run does not duplicate)" {
  make_bundle node-a
  mkdir -p "${RIVETOS_HOME}/.rivetos"
  cat >"${RIVETOS_HOME}/.rivetos/config.yaml" <<'EOF'
# RivetOS Configuration
# Generated by rivetos init
runtime:
  workspace: ~/.rivetos/workspace
EOF
  bash -c '
    source "$1"
    init_paths
    NODE_NAME=node-a
    unpack_enroll_bundle "$2" node-a
    unpack_enroll_bundle "$2" node-a
  ' bash "${NODE_SH}" "${TEST_TMP}/bundle.b64"
  [ -f "${RIVETOS_HOME}/.rivetos/config.yaml.bak" ]
  count="$(grep -cF '# Generated by rivethub-hub enroll' "${RIVETOS_HOME}/.rivetos/config.yaml")"
  [ "${count}" -eq 1 ]
  ncount="$(grep -c 'node_name:' "${RIVETOS_HOME}/.rivetos/config.yaml")"
  [ "${ncount}" -eq 1 ]
  grep -q 'workspace: ~/.rivetos/workspace' "${RIVETOS_HOME}/.rivetos/config.yaml"
}

@test "enroll_via_ssh uses BatchMode ssh and unpacks the remote tarball" {
  make_bundle node-a
  install_ssh_stub
  bash -c '
    source "$1"
    init_paths
    NODE_NAME=node-a
    ADVERTISE_HOST=192.0.2.11
    enroll_via_ssh owner@192.0.2.10 node-a 192.0.2.11
  ' bash "${NODE_SH}"
  [ -f "${RIVETOS_SHARED_DIR}/rivet-ca/issued/node-a.key" ]
  [ "$(stat -c %a "${RIVETOS_SHARED_DIR}/rivet-ca/issued/node-a.key")" = "600" ]
  grep -q "BatchMode=yes" "${TEST_TMP}/ssh.log"
  grep -q "rivethub-hub enroll node-a 192.0.2.11" "${TEST_TMP}/ssh.log"
  # key material from the bundle must not be printed
  ! grep -q "KEYMATERIAL" "${TEST_TMP}/ssh.log"
}

@test "enroll_via_ssh does not call enroll when BatchMode probe fails" {
  make_bundle node-a
  install_ssh_stub
  touch "${TEST_TMP}/ssh-deny"
  run bash -c '
    source "$1"
    init_paths
    enroll_via_ssh owner@192.0.2.10 node-a 192.0.2.11
  ' bash "${NODE_SH}"
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"ssh-copy-id"* ]]
  ! grep -q "enroll" "${TEST_TMP}/ssh.log"
  [ ! -f "${RIVETOS_SHARED_DIR}/rivet-ca/issued/node-a.key" ]
}

# ---------------------------------------------------------------------------
# banner
# ---------------------------------------------------------------------------

@test "banner names status commands, config path, and how to add the next node" {
  run bash -c '
    source "$1"
    init_paths
    FLAG_DOCKER=0
    NODE_NAME=node-a
    RIVET_UID=2000
    HUB_TARGET=owner@192.0.2.10
    print_banner
  ' bash "${NODE_SH}"
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"systemctl status rivetos-agent.service"* ]]
  [[ "${output}" == *"rivetos-agent.service, not rivetos.service"* ]]
  [[ "${output}" == *"rivetos doctor"* ]]
  [[ "${output}" == *"rivetos mesh sync"* ]]
  [[ "${output}" == *"${RIVETOS_HOME}/.rivetos/config.yaml"* ]]
  [[ "${output}" == *"get.rivethub.io/node.sh"* ]]
  [[ "${output}" == *"node-b"* ]]
  [[ "${output}" == *"192.0.2.11"* ]]
  [[ "${output}" == *"bare-metal"* ]]
  [[ "${output}" == *"uid 2000"* ]]
}

@test "banner does not print key material" {
  make_bundle node-a
  bash -c '
    source "$1"
    init_paths
    NODE_NAME=node-a
    unpack_enroll_bundle "$2" node-a
    FLAG_DOCKER=0
    RIVET_UID=2000
    HUB_TARGET=owner@192.0.2.10
    print_banner
  ' bash "${NODE_SH}" "${TEST_TMP}/bundle.b64" \
    >"${TEST_TMP}/banner.out" 2>"${TEST_TMP}/banner.err"
  ! grep -q "KEYMATERIAL" "${TEST_TMP}/banner.out"
  ! grep -q "KEYMATERIAL" "${TEST_TMP}/banner.err"
  grep -q "config.yaml" "${TEST_TMP}/banner.out"
}

# ---------------------------------------------------------------------------
# pins / stubbed main
# ---------------------------------------------------------------------------

@test "agent_image warns and falls back when pin is UNPINNED" {
  export RIVETHUB_PINS_FILE="${BATS_TEST_DIRNAME}/fixtures/pins-unpinned.json"
  run bash -c '
    source "$1"
    init_paths
    agent_image
  ' bash "${NODE_SH}"
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"UNPINNED"* ]]
  [[ "${output}" == *"ghcr.io/philbert440/rivetos:latest"* ]]
}

@test "node_main stubbed install writes layout, unit, node.env, banner" {
  bash "${NODE_SH}" --hub owner@192.0.2.10 --name node-a --advertise-host 192.0.2.11 \
    >"${TEST_TMP}/main.out" 2>"${TEST_TMP}/main.err"
  [ -d "${RIVETOS_SHARED_DIR}/rivet-ca/issued" ]
  [ "$(stat -c %a "${RIVETOS_SHARED_DIR}/rivet-ca/issued")" = "700" ]
  [ -f "${RIVETHUB_ROOT}/node.env" ]
  grep -q "^NODE_NAME=node-a$" "${RIVETHUB_ROOT}/node.env"
  grep -q "^RIVET_UID=2000$" "${RIVETHUB_ROOT}/node.env"
  [ -f "${RIVETHUB_SYSTEMD_DIR}/rivetos-agent.service" ]
  grep -q "^User=rivet$" "${RIVETHUB_SYSTEMD_DIR}/rivetos-agent.service"
  grep -q "EnvironmentFile=" "${RIVETHUB_SYSTEMD_DIR}/rivetos-agent.service"
  grep -q "systemctl status rivetos-agent" "${TEST_TMP}/main.out"
  grep -q "config.yaml" "${TEST_TMP}/main.out"
  ! grep -q "KEYMATERIAL" "${TEST_TMP}/main.out"
  ! grep -q "KEYMATERIAL" "${TEST_TMP}/main.err"
}

@test "--docker writes a host-network docker unit and does not print secrets" {
  export RIVETHUB_PINS_FILE="${BATS_TEST_DIRNAME}/fixtures/pins-unpinned.json"
  bash "${NODE_SH}" --docker --hub owner@192.0.2.10 --name node-b --advertise-host 192.0.2.11 \
    >"${TEST_TMP}/d.out" 2>"${TEST_TMP}/d.err"
  [ -f "${RIVETHUB_SYSTEMD_DIR}/rivetos-agent.service" ]
  grep -q "network host" "${RIVETHUB_SYSTEMD_DIR}/rivetos-agent.service"
  grep -q "ghcr.io/philbert440/rivetos:latest" "${RIVETHUB_SYSTEMD_DIR}/rivetos-agent.service"
  grep -q "docker" "${TEST_TMP}/d.out"
  ! grep -qi "BEGIN PRIVATE KEY" "${TEST_TMP}/d.out"
  ! grep -qi "BEGIN PRIVATE KEY" "${TEST_TMP}/d.err"
}

# ---------------------------------------------------------------------------
# review fixes (B1–B4, R1–R6, minors)
# ---------------------------------------------------------------------------

@test "os-release fixtures are committed" {
  [ -f "${BATS_TEST_DIRNAME}/fixtures/os-release-debian" ]
  [ -f "${BATS_TEST_DIRNAME}/fixtures/os-release-other" ]
}

@test "sourcing node.sh does not invoke node_main" {
  run bash -c '
    source "$1"
    echo SOURCED_OK
  ' bash "${NODE_SH}"
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"SOURCED_OK"* ]]
  [[ "${output}" != *"is installed"* ]]
}

@test "piped bash -s -- -h invokes usage (curl-pipe guard)" {
  run bash -c 'cat "$1" | bash -s -- -h' _ "${NODE_SH}"
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"Usage: node.sh"* ]]
  [[ "${output}" == *"--hub"* ]]
  [[ "${output}" == *"--docker"* ]]
}

@test "piped bash -s stubbed install is not a silent no-op" {
  cat "${NODE_SH}" | env \
    RIVETHUB_TEST=1 \
    RIVETHUB_ROOT="${RIVETHUB_ROOT}" \
    RIVETHUB_DISTRO_DIR="${REPO}" \
    RIVETHUB_SYSTEMD_DIR="${RIVETHUB_SYSTEMD_DIR}" \
    RIVETOS_INSTALL_ROOT="${RIVETOS_INSTALL_ROOT}" \
    RIVETOS_SHARED_DIR="${RIVETOS_SHARED_DIR}" \
    RIVETOS_HOME="${RIVETOS_HOME}" \
    RIVETHUB_OS_RELEASE="${RIVETHUB_OS_RELEASE}" \
    RIVETHUB_ADVERTISE_HOST=192.0.2.11 \
    PATH="${PATH}" \
    bash -s -- --hub owner@192.0.2.10 --name node-a --advertise-host 192.0.2.11 \
    >"${TEST_TMP}/pipe.out" 2>"${TEST_TMP}/pipe.err"
  [ -f "${RIVETHUB_ROOT}/node.env" ]
  grep -q "^NODE_NAME=node-a$" "${RIVETHUB_ROOT}/node.env"
  grep -q "is installed" "${TEST_TMP}/pipe.out"
  grep -q "systemctl status rivetos-agent" "${TEST_TMP}/pipe.out"
}

@test "re-run without --hub resumes HUB_TARGET from node.env" {
  bash "${NODE_SH}" --hub owner@192.0.2.10 --name node-a --advertise-host 192.0.2.11 \
    >"${TEST_TMP}/first.out" 2>"${TEST_TMP}/first.err"
  grep -q "^HUB_TARGET=owner@192.0.2.10$" "${RIVETHUB_ROOT}/node.env"
  run bash "${NODE_SH}" --name node-a --advertise-host 192.0.2.11
  [ "${status}" -eq 0 ]
  [[ "${output}" != *"--hub USER@HOST is required"* ]]
  grep -q "^HUB_TARGET=owner@192.0.2.10$" "${RIVETHUB_ROOT}/node.env"
  grep -q "is installed" <<<"${output}"
}

@test "node_main warns when --name differs from node.env" {
  bash "${NODE_SH}" --hub owner@192.0.2.10 --name node-a --advertise-host 192.0.2.11 \
    >/dev/null 2>"${TEST_TMP}/n1.err"
  run bash "${NODE_SH}" --hub owner@192.0.2.10 --name node-b --advertise-host 192.0.2.11
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"NODE_NAME"* ]]
  [[ "${output}" == *"node-a"* ]]
  [[ "${output}" == *"node-b"* ]]
  grep -q "^NODE_NAME=node-b$" "${RIVETHUB_ROOT}/node.env"
}

@test "re-run with no flags resumes name and hub from node.env" {
  bash "${NODE_SH}" --hub owner@192.0.2.10 --name node-a --advertise-host 192.0.2.11 \
    >/dev/null 2>"${TEST_TMP}/first.err"
  run bash "${NODE_SH}"
  [ "${status}" -eq 0 ]
  [[ "${output}" != *"--hub USER@HOST is required"* ]]
  grep -q "^NODE_NAME=node-a$" "${RIVETHUB_ROOT}/node.env"
  grep -q "^HUB_TARGET=owner@192.0.2.10$" "${RIVETHUB_ROOT}/node.env"
}

@test "run_init_wizard with no answers-file does not quote an empty arg" {
  run bash -c '
    source "$1"
    init_paths
    run_init_wizard
  ' bash "${NODE_SH}"
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"extra=[]"* ]]
  [[ "${output}" != *"extra=['']"* ]]
  [[ "${output}" != *"extra=[\\'\\']"* ]]
}

@test "valid_advertise_host rejects colon-plus-metacharacters and accepts IPv6" {
  run src valid_advertise_host 'x:;id'
  [ "${status}" -ne 0 ]
  run src valid_advertise_host '::1'
  [ "${status}" -eq 0 ]
  run src valid_advertise_host '[::1]'
  [ "${status}" -eq 0 ]
  run src valid_advertise_host 'fe80::1%eth0' # secret-scan-allow
  [ "${status}" -eq 0 ]
  run src valid_advertise_host '::1%eth0;id'
  [ "${status}" -ne 0 ]
}

@test "valid_image_ref rejects shell metacharacters and accepts digest form" {
  run src valid_image_ref 'ghcr.io/x/y;id'
  [ "${status}" -ne 0 ]
  run src valid_image_ref 'ghcr.io/philbert440/rivetos@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
  [ "${status}" -eq 0 ]
  run src valid_image_ref 'ghcr.io/philbert440/rivetos:latest'
  [ "${status}" -eq 0 ]
}

@test "curl-pipe without DISTRO_DIR uses embedded pins" {
  cp "${NODE_SH}" "${TEST_TMP}/node.sh"
  run bash -c '
    unset RIVETHUB_DISTRO_DIR
    unset RIVETHUB_PINS_FILE
    unset RIVETHUB_PINS_URL
    source "$1"
    init_paths
    pin_get rivetos_tag UNPINNED
    pin_get image UNPINNED
  ' bash "${TEST_TMP}/node.sh"
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"UNPINNED"* ]]
  [[ "${output}" == *"ghcr.io/philbert440/rivetos:UNPINNED"* ]]
}

@test "--force replaces an existing checkout; re-run without --force leaves it" {
  bash "${NODE_SH}" --hub owner@192.0.2.10 --name node-a --advertise-host 192.0.2.11 \
    >/dev/null 2>"${TEST_TMP}/i1.err"
  printf '%s\n' '{"name":"keep-me"}' >"${RIVETOS_INSTALL_ROOT}/package.json"
  printf 'KEEP\n' >>"${RIVETOS_INSTALL_ROOT}/package.json"
  bash "${NODE_SH}" --hub owner@192.0.2.10 --name node-a --advertise-host 192.0.2.11 \
    >/dev/null 2>"${TEST_TMP}/i2.err"
  grep -q KEEP "${RIVETOS_INSTALL_ROOT}/package.json"
  bash "${NODE_SH}" --force --hub owner@192.0.2.10 --name node-a --advertise-host 192.0.2.11 \
    >/dev/null 2>"${TEST_TMP}/i3.err"
  [ ! -f "${RIVETOS_INSTALL_ROOT}/package.json" ]
  [ -d "${RIVETOS_INSTALL_ROOT}" ]
  [ -f "${RIVETHUB_SYSTEMD_DIR}/rivetos-agent.service" ]
}

@test "write_baremetal_unit templates custom home/root/shared" {
  bash "${NODE_SH}" --hub owner@192.0.2.10 --name node-a --advertise-host 192.0.2.11 \
    >/dev/null 2>"${TEST_TMP}/unit.err"
  unit="${RIVETHUB_SYSTEMD_DIR}/rivetos-agent.service"
  grep -q "${RIVETOS_HOME}" "${unit}"
  grep -q "${RIVETOS_INSTALL_ROOT}" "${unit}"
  grep -q "${RIVETOS_SHARED_DIR}" "${unit}"
  grep -q "^User=rivet$" "${unit}"
}

@test "merge replaces a pre-existing mesh: key and rewrites storage_dir" {
  make_bundle node-a
  mkdir -p "${RIVETOS_HOME}/.rivetos"
  cat >"${RIVETOS_HOME}/.rivetos/config.yaml" <<'EOF'
# RivetOS Configuration
runtime:
  workspace: ~/.rivetos/workspace
mesh:
  enabled: false
  node_name: "stale"
EOF
  bash -c '
    source "$1"
    init_paths
    NODE_NAME=node-a
    unpack_enroll_bundle "$2" node-a
  ' bash "${NODE_SH}" "${TEST_TMP}/bundle.b64"
  count="$(grep -cF '# Generated by rivethub-hub enroll' "${RIVETOS_HOME}/.rivetos/config.yaml")"
  [ "${count}" -eq 1 ]
  ncount="$(grep -c 'node_name:' "${RIVETOS_HOME}/.rivetos/config.yaml")"
  [ "${ncount}" -eq 1 ]
  grep -q 'node_name: "node-a"' "${RIVETOS_HOME}/.rivetos/config.yaml"
  grep -q "storage_dir: \"${RIVETOS_SHARED_DIR}\"" "${RIVETOS_HOME}/.rivetos/config.yaml"
  grep -q 'workspace: ~/.rivetos/workspace' "${RIVETOS_HOME}/.rivetos/config.yaml"
  ! grep -q 'node_name: "stale"' "${RIVETOS_HOME}/.rivetos/config.yaml"
}

@test "name drift replaces mesh: block and removes stale certs" {
  make_bundle node-a
  bash -c '
    source "$1"
    init_paths
    NODE_NAME=node-a
    unpack_enroll_bundle "$2" node-a
  ' bash "${NODE_SH}" "${TEST_TMP}/bundle.b64"
  [ -f "${RIVETOS_SHARED_DIR}/rivet-ca/issued/node-a.key" ]
  make_bundle node-b
  bash -c '
    source "$1"
    init_paths
    PREV_NODE_NAME=node-a
    NODE_NAME=node-b
    IDENTITY_DRIFT=1
    unpack_enroll_bundle "$2" node-b
  ' bash "${NODE_SH}" "${TEST_TMP}/bundle.b64"
  [ -f "${RIVETOS_SHARED_DIR}/rivet-ca/issued/node-b.key" ]
  [ ! -f "${RIVETOS_SHARED_DIR}/rivet-ca/issued/node-a.key" ]
  count="$(grep -cF '# Generated by rivethub-hub enroll' "${RIVETOS_HOME}/.rivetos/config.yaml")"
  [ "${count}" -eq 1 ]
  grep -q 'node_name: "node-b"' "${RIVETOS_HOME}/.rivetos/config.yaml"
  ! grep -q 'node_name: "node-a"' "${RIVETOS_HOME}/.rivetos/config.yaml"
}

@test "enroll_via_ssh fails when the remote enroll command fails" {
  make_bundle node-a
  install_ssh_stub
  touch "${TEST_TMP}/ssh-enroll-fail"
  run bash -c '
    source "$1"
    init_paths
    enroll_via_ssh owner@192.0.2.10 node-a 192.0.2.11
  ' bash "${NODE_SH}"
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"enroll failed"* ]]
  [ ! -f "${RIVETOS_SHARED_DIR}/rivet-ca/issued/node-a.key" ]
}

@test "enroll_via_ssh fails on an empty tarball" {
  make_bundle node-a
  install_ssh_stub
  touch "${TEST_TMP}/ssh-enroll-empty"
  run bash -c '
    source "$1"
    init_paths
    enroll_via_ssh owner@192.0.2.10 node-a 192.0.2.11
  ' bash "${NODE_SH}"
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"empty tarball"* ]]
  [ ! -f "${RIVETOS_SHARED_DIR}/rivet-ca/issued/node-a.key" ]
}

@test "unpack refuses tarball members with .. paths" {
  python3 - "${TEST_TMP}/evil.tgz" <<'PY'
import io, sys, tarfile
path = sys.argv[1]
with tarfile.open(path, "w:gz") as tf:
    info = tarfile.TarInfo("../evil.txt")
    data = b"nope\n"
    info.size = len(data)
    tf.addfile(info, io.BytesIO(data))
PY
  base64 -w0 <"${TEST_TMP}/evil.tgz" >"${TEST_TMP}/evil.b64"
  printf '\n' >>"${TEST_TMP}/evil.b64"
  run bash -c '
    source "$1"
    init_paths
    NODE_NAME=node-a
    unpack_enroll_bundle "$2" node-a
  ' bash "${NODE_SH}" "${TEST_TMP}/evil.b64"
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"unsafe"* ]]
}

@test "ensure_rivet_shared_link warns when the symlink points elsewhere" {
  link="${TEST_TMP}/rivet-shared"
  other="${TEST_TMP}/other-shared"
  mkdir -p "${other}"
  ln -s "${other}" "${link}"
  run bash -c '
    export RIVETHUB_RIVET_SHARED_LINK="$2"
    source "$1"
    init_paths
    ensure_rivet_shared_link
  ' bash "${NODE_SH}" "${link}"
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"points at"* ]]
  [[ "$(readlink "${link}")" == "${other}" ]]
}

@test "restart_or_enable_agent try-restarts an already-active unit" {
  cat >"${TEST_TMP}/bin/systemctl" <<EOF
#!/usr/bin/env bash
echo "systemctl \$*" >>"${TEST_TMP}/systemctl.log"
if [[ "\$1" == "is-active" ]]; then
  if [[ -f "${TEST_TMP}/unit-active" ]]; then
    exit 0
  fi
  exit 3
fi
exit 0
EOF
  chmod +x "${TEST_TMP}/bin/systemctl"
  touch "${TEST_TMP}/unit-active"
  bash -c '
    source "$1"
    init_paths
    restart_or_enable_agent
  ' bash "${NODE_SH}"
  grep -q "try-restart" "${TEST_TMP}/systemctl.log"
  grep -q "enable rivetos-agent.service" "${TEST_TMP}/systemctl.log"
  ! grep -q "enable --now" "${TEST_TMP}/systemctl.log"
}

@test "restart_or_enable_agent enable --now when the unit is inactive" {
  cat >"${TEST_TMP}/bin/systemctl" <<EOF
#!/usr/bin/env bash
echo "systemctl \$*" >>"${TEST_TMP}/systemctl.log"
if [[ "\$1" == "is-active" ]]; then
  exit 3
fi
exit 0
EOF
  chmod +x "${TEST_TMP}/bin/systemctl"
  bash -c '
    source "$1"
    init_paths
    restart_or_enable_agent
  ' bash "${NODE_SH}"
  grep -q "enable --now rivetos-agent.service" "${TEST_TMP}/systemctl.log"
}

@test "unpack accepts a real rivethub-hub enroll tarball (stdout contract)" {
  datahub="${TEST_TMP}/datahub"
  mkdir -p "${datahub}"
  env RIVETHUB_ROOT="${datahub}" \
    RIVETHUB_CA_SCRIPT="${BATS_TEST_DIRNAME}/fixtures/rivet-ca.sh" \
    RIVETHUB_ADVERTISE_HOST="192.0.2.10" \
    RIVETHUB_NODE_NAME="datahub" \
    bash "${REPO}/bin/rivethub-hub" ca-init
  env RIVETHUB_ROOT="${datahub}" \
    RIVETHUB_CA_SCRIPT="${BATS_TEST_DIRNAME}/fixtures/rivet-ca.sh" \
    RIVETHUB_ADVERTISE_HOST="192.0.2.10" \
    RIVETHUB_NODE_NAME="datahub" \
    bash "${REPO}/bin/rivethub-hub" enroll node-a 192.0.2.11 \
    >"${TEST_TMP}/hub.b64" 2>"${TEST_TMP}/hub.err"
  [ -s "${TEST_TMP}/hub.b64" ]
  ! grep -q "rivethub-hub:" "${TEST_TMP}/hub.b64"
  listing="$(base64 -d <"${TEST_TMP}/hub.b64" | tar -tzf - | sed 's|^\./||' | sort | tr -d '\r')"
  expected="$(printf '%s\n' ca-chain.pem mesh.json node-a.crt node-a.key node-config-snippet.yaml)"
  [ "${listing}" = "${expected}" ]
  mkdir -p "${TEST_TMP}/hub-unpack"
  base64 -d <"${TEST_TMP}/hub.b64" | tar -xzf - -C "${TEST_TMP}/hub-unpack"
  grep -q '# Generated by rivethub-hub enroll' "${TEST_TMP}/hub-unpack/node-config-snippet.yaml"
  grep -q 'node_name: "node-a"' "${TEST_TMP}/hub-unpack/node-config-snippet.yaml"
  grep -q 'storage_dir: "/var/lib/rivethub/shared"' "${TEST_TMP}/hub-unpack/node-config-snippet.yaml"
  bash -c '
    source "$1"
    init_paths
    NODE_NAME=node-a
    unpack_enroll_bundle "$2" node-a
  ' bash "${NODE_SH}" "${TEST_TMP}/hub.b64"
  [ -f "${RIVETOS_SHARED_DIR}/rivet-ca/issued/node-a.key" ]
  [ "$(stat -c %a "${RIVETOS_SHARED_DIR}/rivet-ca/issued/node-a.key")" = "600" ]
  grep -q "storage_dir: \"${RIVETOS_SHARED_DIR}\"" "${RIVETOS_HOME}/.rivetos/config.yaml"
  grep -q '# Generated by rivethub-hub enroll' "${RIVETOS_HOME}/.rivetos/config.yaml"
}

# ---------------------------------------------------------------------------
# e2e F4 — --yes / wizard parity
# ---------------------------------------------------------------------------

@test "parse_args records --yes / -y" {
  out="$(parse_print --yes --hub owner@192.0.2.10)"
  [[ "${out}" == *"yes=1"* ]]
  [[ "${out}" == *"hub=owner@192.0.2.10"* ]]
  out="$(parse_print -y --hub owner@192.0.2.10)"
  [[ "${out}" == *"yes=1"* ]]
}

@test "non-TTY without --hub lists hub env/flag in one unanswered error" {
  unset RIVETHUB_HUB RIVETHUB_PROMPT_IN
  run bash "${NODE_SH}" --name node-a --advertise-host 192.0.2.11
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"Unanswered questions"* ]]
  [[ "${output}" == *"--hub"* ]]
  [[ "${output}" == *"RIVETHUB_HUB"* ]]
  [ ! -f "${RIVETHUB_ROOT}/node.env" ]
}

@test "--yes on non-TTY still requires --hub (no default)" {
  unset RIVETHUB_HUB RIVETHUB_PROMPT_IN
  run bash "${NODE_SH}" --yes --name node-a --advertise-host 192.0.2.11
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"Unanswered questions"* ]]
  [[ "${output}" == *"--hub"* ]]
}

@test "--yes with --hub installs without a prompt source" {
  bash "${NODE_SH}" --yes --hub owner@192.0.2.10 --name node-a --advertise-host 192.0.2.11 \
    >"${TEST_TMP}/yes.out" 2>"${TEST_TMP}/yes.err"
  [ -f "${RIVETHUB_ROOT}/node.env" ]
  grep -q "^HUB_TARGET=owner@192.0.2.10$" "${RIVETHUB_ROOT}/node.env"
  grep -q "^NODE_NAME=node-a$" "${RIVETHUB_ROOT}/node.env"
  grep -q "proceeding (--yes)" "${TEST_TMP}/yes.err"
  grep -q "rivetos-agent.service" "${TEST_TMP}/yes.out"
}

@test "wizard reads scripted answers from RIVETHUB_PROMPT_IN" {
  printf '%s\n' 'owner@192.0.2.10' 'node-scripted' '192.0.2.11' 'yes' >"${TEST_TMP}/answers"
  out="$(
    unset RIVETHUB_HUB RIVETHUB_ADVERTISE_HOST
    RIVETHUB_PROMPT_IN="${TEST_TMP}/answers" bash -c '
      source "$1"
      parse_args
      init_paths
      load_node_env
      run_wizard_flow
      confirm_or_die
      printf "hub=%s name=%s host=%s action=%s\n" \
        "${HUB_TARGET}" "${NODE_NAME}" "${ADVERTISE_HOST}" "${WIZARD_ACTION}"
    ' bash "${NODE_SH}"
  )"
  [[ "${out}" == *"hub=owner@192.0.2.10"* ]]
  [[ "${out}" == *"name=node-scripted"* ]]
  [[ "${out}" == *"host=192.0.2.11"* ]]
}

@test "confirm_or_die without --yes refuses no" {
  printf 'no\n' >"${TEST_TMP}/answers"
  run env RIVETHUB_PROMPT_IN="${TEST_TMP}/answers" bash -c '
    source "$1"
    FLAG_YES=0
    confirm_or_die
  ' bash "${NODE_SH}"
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"aborted"* ]]
}

# ---------------------------------------------------------------------------
# e2e F5 — rivet home owner
# ---------------------------------------------------------------------------

@test "preflight_rivet_home accepts an existing home in test mode" {
  mkdir -p "${RIVETOS_HOME}"
  run bash -c '
    source "$1"
    init_paths
    preflight_rivet_home
  ' bash "${NODE_SH}"
  [ "${status}" -eq 0 ]
}

@test "preflight_rivet_home refuses a missing home" {
  run bash -c '
    source "$1"
    init_paths
    RIVET_HOME="$TEST_TMP/no-such-home"
    preflight_rivet_home
  ' bash "${NODE_SH}"
  [ "${status}" -ne 0 ]
  [[ "${output}" == *"missing"* ]]
}

@test "node_main creates rivet home before the owner preflight" {
  bash "${NODE_SH}" --yes --hub owner@192.0.2.10 --name node-a --advertise-host 192.0.2.11 \
    >/dev/null 2>"${TEST_TMP}/home.err"
  [ -d "${RIVETOS_HOME}" ]
}

# ---------------------------------------------------------------------------
# e2e F6 — unit name rivetos-agent.service
# ---------------------------------------------------------------------------

@test "banner and unit file use rivetos-agent.service not rivetos.service" {
  bash "${NODE_SH}" --yes --hub owner@192.0.2.10 --name node-a --advertise-host 192.0.2.11 \
    >"${TEST_TMP}/unit.out" 2>"${TEST_TMP}/unit.err"
  [ -f "${RIVETHUB_SYSTEMD_DIR}/rivetos-agent.service" ]
  [ ! -f "${RIVETHUB_SYSTEMD_DIR}/rivetos.service" ]
  grep -q "rivetos-agent.service" "${TEST_TMP}/unit.out"
  grep -q "not rivetos.service" "${TEST_TMP}/unit.out"
  grep -q "^SyslogIdentifier=rivetos-agent$" "${RIVETHUB_SYSTEMD_DIR}/rivetos-agent.service"
}

# ---------------------------------------------------------------------------
# e2e F7 — rivet ssh keypair + hubside install
# ---------------------------------------------------------------------------

@test "node_main generates a rivet ssh keypair and records it in node.env" {
  bash "${NODE_SH}" --yes --hub owner@192.0.2.10 --name node-a --advertise-host 192.0.2.11 \
    >/dev/null 2>"${TEST_TMP}/k.err"
  [ -f "${RIVETOS_HOME}/.ssh/id_ed25519" ]
  [ -f "${RIVETOS_HOME}/.ssh/id_ed25519.pub" ]
  [ "$(stat -c %a "${RIVETOS_HOME}/.ssh/id_ed25519")" = "600" ]
  grep -q "^RIVET_SSH_KEY=${RIVETOS_HOME}/.ssh/id_ed25519$" "${RIVETHUB_ROOT}/node.env"
  grep -q "^HUB_TARGET=owner@192.0.2.10$" "${RIVETHUB_ROOT}/node.env"
  grep -q "rivet ssh key" "${TEST_TMP}/k.err"
}

@test "ensure_rivet_ssh_key is idempotent" {
  bash -c '
    source "$1"
    init_paths
    ensure_rivet_ssh_key
    cp "$RIVET_HOME/.ssh/id_ed25519.pub" "$TEST_TMP/pub1"
    ensure_rivet_ssh_key
    cmp -s "$RIVET_HOME/.ssh/id_ed25519.pub" "$TEST_TMP/pub1"
  ' bash "${NODE_SH}"
}

@test "install_rivet_key_on_hub copies the pubkey over BatchMode ssh" {
  install_ssh_stub
  bash -c '
    source "$1"
    init_paths
    ensure_rivet_ssh_key
  ' bash "${NODE_SH}"
  run env RIVETHUB_TEST_SSH_KEY=1 bash -c '
    source "$1"
    init_paths
    install_rivet_key_on_hub owner@192.0.2.10
  ' bash "${NODE_SH}"
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"installed rivet pubkey"* ]]
  grep -q "BatchMode=yes" "${TEST_TMP}/ssh.log"
  [ -s "${TEST_TMP}/hub-authorized-keys" ]
  grep -q "ssh-ed25519" "${TEST_TMP}/hub-authorized-keys"
}

@test "banner documents day-2 mesh sync/renew as rivet" {
  run bash -c '
    source "$1"
    init_paths
    FLAG_DOCKER=0
    NODE_NAME=node-a
    RIVET_UID=2000
    HUB_TARGET=owner@192.0.2.10
    print_banner
  ' bash "${NODE_SH}"
  [ "${status}" -eq 0 ]
  [[ "${output}" == *"sudo -u rivet -H rivetos mesh sync"* ]]
  [[ "${output}" == *"sudo -u rivet -H rivetos mesh renew"* ]]
  [[ "${output}" == *"id_ed25519"* ]]
}
