/**
 * Compile a flows canvas graph into the workflow directory the engine already
 * runs: workflow.yaml, run.ts, agents/*.md, scripts/*.sh, flows.json.
 */

import type { WorkflowField } from '@rivetos/types'
import {
  FLOW_START_ID,
  nodeById,
  outgoingIds,
  slugify,
  topoSort,
  type FlowAuthorGraph,
  type FlowAuthorNode,
} from './flow-graph.js'

export const FLOWS_FILE = 'flows.json'
export const RUN_TS_MARKER = '@generated by RivetHub flows canvas'

export interface CompileMeta {
  id: string
  name: string
  version: string
  description?: string
  input: WorkflowField[]
  output: WorkflowField[]
  budgets?: { maxTokens?: number; maxCost?: number; maxConcurrentRuns?: number }
}

export interface CompiledWorkflow {
  files: Record<string, string>
}

function ident(id: string): string {
  const s = id.replace(/[^a-zA-Z0-9_]/g, '_')
  return /^[A-Za-z_]/.test(s) ? s : `s_${s}`
}

function yamlScalar(v: string): string {
  if (/^[A-Za-z0-9_./-]+$/.test(v) && !['true', 'false', 'null'].includes(v)) return v
  return JSON.stringify(v)
}

function yamlFields(fields: WorkflowField[], indent: string): string {
  if (fields.length === 0) return `${indent}[]\n`
  return fields
    .map((f) => {
      const req = f.required === true ? `\n${indent}  required: true` : ''
      const desc = f.description ? `\n${indent}  description: ${yamlScalar(f.description)}` : ''
      return `${indent}- name: ${yamlScalar(f.name)}\n${indent}  type: ${f.type}${req}${desc}`
    })
    .join('\n')
}

function defaultInput(): WorkflowField[] {
  return [{ name: 'message', type: 'string', required: true, description: 'Input message' }]
}

function defaultOutput(): WorkflowField[] {
  return [{ name: 'result', type: 'string', description: 'Final result' }]
}

function agentFile(node: FlowAuthorNode): string {
  const tools = node.tools ?? []
  const lines = ['---', `tools: [${tools.map((t) => yamlScalar(t)).join(', ')}]`]
  if (node.model) lines.push(`model: ${yamlScalar(node.model)}`)
  if (node.maxTurns !== undefined) lines.push(`maxTurns: ${String(node.maxTurns)}`)
  lines.push('---', '', node.prompt?.trim() || 'You are a workflow agent.', '')
  return lines.join('\n')
}

function scriptStub(node: FlowAuthorNode): string {
  return `#!/bin/sh
set -eu
# Deterministic step "${node.label}" — no model, no tokens.
# Case directory is the working directory for this run.
echo "ok"
`
}

function emitStep(node: FlowAuthorNode): string {
  const label = JSON.stringify(node.id)
  switch (node.kind) {
    case 'agent': {
      const agent = JSON.stringify(node.agentName || slugify(node.label) || node.id)
      return `  const ${ident(node.id)} = await step.agent(${label}, {
    agent: ${agent},
    prompt: ${JSON.stringify(node.label)},
    out: ['result'],
  })`
    }
    case 'run': {
      const script = JSON.stringify(node.scriptPath || `scripts/${node.id}.sh`)
      return `  const ${ident(node.id)} = await step.run(${label}, { script: ${script} })`
    }
    case 'human': {
      const prompt = JSON.stringify(node.gatePrompt || node.label)
      const fields = JSON.stringify(node.gateFields?.length ? node.gateFields : ['approved'])
      return `  const ${ident(node.id)} = await step.human(${label}, {
    prompt: ${prompt},
    fields: ${fields},
  })`
    }
    case 'call': {
      const ref = JSON.stringify(node.callRef || node.label)
      return `  const ${ident(node.id)} = await step.call(${label}, ${ref}, ctx.input)`
    }
    case 'done':
      return `  await step.done({ result: ${ident(node.id)}_unused })`.replace(
        `result: ${ident(node.id)}_unused`,
        'result: true',
      )
    default:
      return `  // ${node.kind} ${node.id}`
  }
}

function emitParallel(
  graph: FlowAuthorGraph,
  node: FlowAuthorNode,
  kids: FlowAuthorNode[],
): string {
  if (kids.length === 0) return `  // parallel ${JSON.stringify(node.id)} has no branches`
  const branches = kids.map((kid) => {
    const body = emitStep(kid).replace(/^\s+/, '      ')
    return `    async (step) => {
${body}
      return ${kid.kind === 'done' ? '{}' : ident(kid.id)}
    }`
  })
  return `  await step.parallel(${JSON.stringify(node.id)}, [
${branches.join(',\n')}
  ])`
}

export function compileFlow(graph: FlowAuthorGraph, meta: CompileMeta): CompiledWorkflow {
  const files: Record<string, string> = {}
  const order = topoSort(graph)
  const skip = new Set<string>()
  const outlineNodes: FlowAuthorNode[] = []
  const stepLines: string[] = []
  let emittedDone = false

  for (const id of order) {
    if (id === FLOW_START_ID) continue
    if (skip.has(id)) continue
    const node = nodeById(graph, id)
    if (!node) continue
    outlineNodes.push(node)
    if (node.kind === 'parallel') {
      const kids = outgoingIds(graph, id)
        .map((kid) => nodeById(graph, kid))
        .filter((n): n is FlowAuthorNode => Boolean(n))
      for (const k of kids) skip.add(k.id)
      stepLines.push(emitParallel(graph, node, kids))
      continue
    }
    if (node.kind === 'done') {
      stepLines.push('  await step.done({ result: true })')
      emittedDone = true
      continue
    }
    stepLines.push(emitStep(node))
  }
  if (!emittedDone) stepLines.push('  await step.done({ result: true })')

  const input = meta.input.length > 0 ? meta.input : defaultInput()
  const output = meta.output.length > 0 ? meta.output : defaultOutput()
  const outlineYaml = outlineNodes
    .map((n) => {
      const kind = n.kind === 'start' ? 'run' : n.kind
      return `  - id: ${yamlScalar(n.id)}\n    kind: ${kind}\n    label: ${yamlScalar(n.label)}`
    })
    .join('\n')

  let budgets = ''
  if (meta.budgets?.maxTokens !== undefined) {
    budgets += `  maxTokens: ${String(meta.budgets.maxTokens)}\n`
  }
  if (meta.budgets?.maxCost !== undefined) {
    budgets += `  maxCost: ${String(meta.budgets.maxCost)}\n`
  }
  if (meta.budgets?.maxConcurrentRuns !== undefined) {
    budgets += `  maxConcurrentRuns: ${String(meta.budgets.maxConcurrentRuns)}\n`
  }

  files['workflow.yaml'] =
    `id: ${yamlScalar(meta.id)}
version: ${yamlScalar(meta.version)}
name: ${yamlScalar(meta.name)}
description: ${yamlScalar(meta.description ?? meta.name)}
input:
${yamlFields(input, '  ')}
output:
${yamlFields(output, '  ')}
outline:
${outlineYaml || '  []'}
${budgets ? `budgets:\n${budgets}` : ''}`.trimEnd() + '\n'

  files['run.ts'] = `/** ${RUN_TS_MARKER}. Do not edit — Save from the canvas. */
import type { Step } from '@rivetos/workflows'

export default async function run(
  step: Step,
  ctx: { input: Record<string, unknown> },
): Promise<void> {
  void ctx
${stepLines.join('\n\n')}
}
`

  files[FLOWS_FILE] =
    `${JSON.stringify({ version: 1, nodes: graph.nodes, edges: graph.edges }, null, 2)}\n`

  for (const n of graph.nodes) {
    if (n.kind === 'agent') {
      const stem = n.agentName || slugify(n.label) || n.id
      files[`agents/${stem}.md`] = agentFile(n)
    }
    if (n.kind === 'run') {
      const path = n.scriptPath || `scripts/${n.id}.sh`
      files[path] = scriptStub(n)
    }
  }

  return { files }
}

export function parseFlowsFile(text: string): FlowAuthorGraph {
  const raw: unknown = JSON.parse(text)
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    throw new Error('flows.json: expected object')
  }
  const o = raw as { version?: unknown; nodes?: unknown; edges?: unknown }
  if (!Array.isArray(o.nodes) || !Array.isArray(o.edges)) {
    throw new Error('flows.json: nodes and edges required')
  }
  return { nodes: o.nodes as FlowAuthorGraph['nodes'], edges: o.edges as FlowAuthorGraph['edges'] }
}
