/**
 * Compile a flows canvas graph into the workflow directory the engine already
 * runs: workflow.yaml, run.ts, agents/*.md, scripts/*.sh, flows.json.
 *
 * Engine semantics (verified in this repo):
 * - `agents/<stem>.md` body is the agent system prompt (`AgentDef.prompt` in
 *   packages/workflows/src/types.ts and loader.ts).
 * - `step.agent({ prompt })` is the per-invocation user/task message. The host
 *   executor concatenates system + user into the task goal
 *   (packages/core/src/domain/workflows/agent-executor.ts).
 * - `step.done(output)` takes explicit output fields. Hand-authored recipes
 *   thread step results (`await step.done({ result: greet.result })` in
 *   packages/workflows/src/scaffold.ts and workflows/hello-world/run.ts).
 */

import type { WorkflowField } from '@rivetos/types'
import {
  FLOW_START_ID,
  incomingIds,
  nodeById,
  outgoingIds,
  reachableFromStart,
  slugify,
  topoSort,
  type FlowAuthorGraph,
  type FlowAuthorKind,
  type FlowAuthorNode,
} from './flow-graph.js'

export class FlowCompileError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'FlowCompileError'
  }
}

export const FLOWS_FILE = 'flows.json'
export const RUN_TS_MARKER = '@generated by RivetHub flows canvas'

const RESERVED_WORKFLOW_FILES = new Set(['run.ts', 'flows.json', 'workflow.yaml'])
const RESERVED_IDENTS = new Set(['__rivetOutputs', '__r', 'step', 'ctx'])

export interface CompileMeta {
  id: string
  name: string
  version: string
  description?: string
  input: WorkflowField[]
  output: WorkflowField[]
  budgets?: { maxTokens?: number; maxCost?: number; maxConcurrentRuns?: number }
  /** When non-empty, Call nodes must reference one of these workflow ids. */
  knownWorkflowIds?: string[]
}

export interface CompiledWorkflow {
  files: Record<string, string>
  /** Paths that must not overwrite an existing file (script stubs). */
  createOnly: string[]
  /** Canvas-owned agent/script paths recorded in flows.json for prune. */
  owned: string[]
}

function ident(id: string): string {
  const s = id.replace(/[^a-zA-Z0-9_]/g, '_')
  return /^[A-Za-z_]/.test(s) ? s : `s_${s}`
}

function looksLikeYamlNumberOrDate(v: string): boolean {
  if (/^[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?$/.test(v)) return true
  if (/^\d{4}-\d{2}-\d{2}(?:[Tt ].*)?$/.test(v)) return true
  return false
}

const YAML_RESERVED = new Set([
  'true',
  'false',
  'null',
  'yes',
  'no',
  'on',
  'off',
  'y',
  'n',
  '~',
  '.inf',
  '-.inf',
  '+.inf',
  '.nan',
])

/** Quote anything a YAML 1.1 parser would not treat as a plain string. */
export function yamlScalar(v: string): string {
  const lower = v.toLowerCase()
  if (YAML_RESERVED.has(lower)) return JSON.stringify(v)
  if (looksLikeYamlNumberOrDate(v)) return JSON.stringify(v)
  if (/^[A-Za-z_][A-Za-z0-9_./-]*$/.test(v)) return v
  return JSON.stringify(v)
}

function yamlFields(fields: WorkflowField[], indent: string): string {
  if (fields.length === 0) return `${indent}[]\n`
  return fields
    .map((f) => {
      const req = f.required === true ? `\n${indent}  required: true` : ''
      const desc = f.description ? `\n${indent}  description: ${yamlScalar(f.description)}` : ''
      return `${indent}- name: ${yamlScalar(f.name)}\n${indent}  type: ${f.type}${req}${desc}`
    })
    .join('\n')
}

function defaultInput(): WorkflowField[] {
  return [{ name: 'message', type: 'string', required: true, description: 'Input message' }]
}

function defaultOutput(): WorkflowField[] {
  return [{ name: 'result', type: 'string', description: 'Final result' }]
}

function agentFile(node: FlowAuthorNode): string {
  const tools = node.tools ?? []
  const lines = ['---', `tools: [${tools.map((t) => yamlScalar(t)).join(', ')}]`]
  if (node.model) lines.push(`model: ${yamlScalar(node.model)}`)
  if (node.maxTurns !== undefined) lines.push(`maxTurns: ${String(node.maxTurns)}`)
  lines.push('---', '')
  lines.push(`<!-- ${RUN_TS_MARKER} -->`, '')
  lines.push(node.prompt?.trim() || 'You are a workflow agent.', '')
  return lines.join('\n')
}

function scriptStub(node: FlowAuthorNode): string {
  return `#!/bin/sh
set -eu
# ${RUN_TS_MARKER}
# Deterministic step "${node.label}" — no model, no tokens.
# Case directory is the working directory for this run.
echo "ok"
`
}

function normalizeRel(path: string): string {
  return path.replace(/\\/g, '/').replace(/\/+/g, '/')
}

/** Same rules as assertSafeRelPath, without throwing (parse/prune context). */
function isSafeRelPath(path: string): boolean {
  const n = normalizeRel(path).replace(/^\.\//, '')
  if (!n) return false
  if (n.startsWith('/') || /^[a-zA-Z]:/.test(n)) return false
  const parts = n.split('/')
  if (parts.some((p) => p === '..' || p === '')) return false
  if (RESERVED_WORKFLOW_FILES.has(n)) return false
  return true
}

export function assertSafeRelPath(path: string, nodeId: string): void {
  const n = normalizeRel(path).replace(/^\.\//, '')
  if (!n) {
    throw new FlowCompileError(`empty path on "${nodeId}"`)
  }
  if (n.startsWith('/') || /^[a-zA-Z]:/.test(n)) {
    throw new FlowCompileError(`absolute path ${JSON.stringify(path)} on "${nodeId}"`)
  }
  const parts = n.split('/')
  if (parts.some((p) => p === '..' || p === '')) {
    throw new FlowCompileError(
      `path ${JSON.stringify(path)} on "${nodeId}" escapes the workflow dir`,
    )
  }
  if (RESERVED_WORKFLOW_FILES.has(n)) {
    throw new FlowCompileError(
      `path ${JSON.stringify(path)} on "${nodeId}" collides with a compiled file`,
    )
  }
}

export function assertSafeAgentStem(stem: string, nodeId: string): void {
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(stem)) {
    throw new FlowCompileError(`unsafe agent name ${JSON.stringify(stem)} on "${nodeId}"`)
  }
}

function agentStem(node: FlowAuthorNode): string {
  return node.agentName || slugify(node.label) || node.id
}

function scriptPathOf(node: FlowAuthorNode): string {
  return node.scriptPath || `scripts/${node.id}.sh`
}

function kahnLeftover(graph: FlowAuthorGraph, reachable: Set<string>): string[] {
  const ids = [...reachable]
  const incoming = new Map<string, number>()
  const outgoing = new Map<string, string[]>()
  for (const id of ids) {
    incoming.set(id, 0)
    outgoing.set(id, [])
  }
  for (const e of graph.edges) {
    if (!reachable.has(e.from) || !reachable.has(e.to)) continue
    incoming.set(e.to, (incoming.get(e.to) ?? 0) + 1)
    outgoing.get(e.from)!.push(e.to)
  }
  const queue: string[] = []
  for (const id of ids) {
    if ((incoming.get(id) ?? 0) === 0) queue.push(id)
  }
  const seen = new Set<string>()
  while (queue.length > 0) {
    const id = queue.shift()!
    seen.add(id)
    for (const nxt of outgoing.get(id) ?? []) {
      const n = (incoming.get(nxt) ?? 1) - 1
      incoming.set(nxt, n)
      if (n === 0) queue.push(nxt)
    }
  }
  return ids.filter((id) => !seen.has(id))
}

function validateFlow(graph: FlowAuthorGraph, meta: CompileMeta): void {
  const ids = new Set<string>()
  for (const n of graph.nodes) {
    if (ids.has(n.id)) throw new FlowCompileError(`duplicate node id "${n.id}"`)
    ids.add(n.id)
  }
  if (!graph.nodes.some((n) => n.id === FLOW_START_ID && n.kind === 'start')) {
    throw new FlowCompileError('graph is missing a start node')
  }
  for (const e of graph.edges) {
    if (!ids.has(e.from) || !ids.has(e.to)) {
      throw new FlowCompileError(`dangling edge "${e.id}" (${e.from} → ${e.to})`)
    }
  }
  const reachable = reachableFromStart(graph)
  const leftover = kahnLeftover(graph, reachable)
  if (leftover.length > 0) {
    throw new FlowCompileError(
      `cycle involving ${leftover.map((id) => JSON.stringify(id)).join(', ')}`,
    )
  }

  const idents = new Map<string, string>()
  const emittedPaths = new Map<string, string>()
  for (const n of graph.nodes) {
    if (!reachable.has(n.id) || n.id === FLOW_START_ID) continue
    const i = ident(n.id)
    if (RESERVED_IDENTS.has(i)) {
      throw new FlowCompileError(`reserved ident ${JSON.stringify(i)} from node "${n.id}"`)
    }
    if (n.kind !== 'done') {
      const prev = idents.get(i)
      if (prev && prev !== n.id) {
        throw new FlowCompileError(`ident collision: "${prev}" and "${n.id}" both compile as ${i}`)
      }
      idents.set(i, n.id)
    }
    if (n.kind === 'run') {
      const path = scriptPathOf(n)
      assertSafeRelPath(path, n.id)
      const prev = emittedPaths.get(path)
      if (prev) {
        throw new FlowCompileError(`duplicate emitted path "${path}" ("${prev}" and "${n.id}")`)
      }
      emittedPaths.set(path, n.id)
    }
    if (n.kind === 'agent') {
      const stem = agentStem(n)
      assertSafeAgentStem(stem, n.id)
      const path = `agents/${stem}.md`
      const prev = emittedPaths.get(path)
      if (prev) {
        throw new FlowCompileError(`duplicate emitted path "${path}" ("${prev}" and "${n.id}")`)
      }
      emittedPaths.set(path, n.id)
    }
    if (n.kind === 'call') {
      const ref = (n.callRef ?? '').trim()
      if (!ref) {
        throw new FlowCompileError(`call "${n.id}" has an empty workflow id`)
      }
      const known = meta.knownWorkflowIds
      if (known && known.length > 0 && !known.includes(ref)) {
        throw new FlowCompileError(
          `call "${n.id}" references unknown workflow ${JSON.stringify(ref)}`,
        )
      }
    }
  }
}

function ownedFromNodes(nodes: FlowAuthorNode[], reachable: Set<string>): string[] {
  const out: string[] = []
  for (const n of nodes) {
    if (!reachable.has(n.id) && n.id !== FLOW_START_ID) continue
    if (n.kind === 'agent') out.push(`agents/${agentStem(n)}.md`)
    if (n.kind === 'run') out.push(scriptPathOf(n))
  }
  return out
}

/**
 * Canvas-owned agent/script paths from a previous flows.json. Prefers the
 * `owned` manifest; old files without it derive paths from nodes so prune
 * still cannot touch hand-authored files the canvas never emitted.
 */
export function ownedPathsFromFlowsFile(text: string): string[] | undefined {
  try {
    const raw: unknown = JSON.parse(text)
    if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return undefined
    const o = raw as { owned?: unknown; nodes?: unknown }
    if ('owned' in o) {
      if (!Array.isArray(o.owned) || !o.owned.every((p) => typeof p === 'string')) return []
      return o.owned.filter(
        (p) => (p.startsWith('agents/') || p.startsWith('scripts/')) && isSafeRelPath(p),
      )
    }
    if (!Array.isArray(o.nodes)) return undefined
    const derived: string[] = []
    for (const item of o.nodes) {
      if (!item || typeof item !== 'object') continue
      const n = item as Record<string, unknown>
      if (n.kind === 'agent') {
        const stem =
          (typeof n.agentName === 'string' && n.agentName) ||
          (typeof n.label === 'string' ? slugify(n.label) : '') ||
          (typeof n.id === 'string' ? n.id : '')
        if (stem) {
          const path = `agents/${stem}.md`
          if (isSafeRelPath(path)) derived.push(path)
        }
      }
      if (n.kind === 'run') {
        const path =
          typeof n.scriptPath === 'string' && n.scriptPath
            ? n.scriptPath
            : typeof n.id === 'string'
              ? `scripts/${n.id}.sh`
              : ''
        if (path && isSafeRelPath(path)) derived.push(path)
      }
    }
    return derived
  } catch {
    return undefined
  }
}

/** Paths recorded as canvas-owned last save that the new compile no longer emits. */
export function pathsToPrune(previousOwned: string[] | undefined, nextOwned: string[]): string[] {
  if (!previousOwned || previousOwned.length === 0) return []
  const keep = new Set(nextOwned)
  return previousOwned.filter((p) => !keep.has(p))
}

/** Prefix every line, preserving relative indent (emitStep is already 2-space). */
function indentLines(s: string, extra: string): string {
  return s
    .split('\n')
    .map((line) => (line.length === 0 ? '' : extra + line))
    .join('\n')
}

function emitStep(node: FlowAuthorNode): string {
  const label = JSON.stringify(node.id)
  switch (node.kind) {
    case 'agent': {
      const agent = JSON.stringify(agentStem(node))
      // Instructions are the system prompt in agents/<stem>.md. step.prompt is
      // the user/task message (agent-executor concatenates both). Emit the
      // authored Instructions here so run.ts carries the prompt content; fall
      // back to the node label when Instructions are empty.
      const prompt = JSON.stringify(node.prompt?.trim() || node.label)
      return `  const ${ident(node.id)} = await step.agent(${label}, {
    agent: ${agent},
    prompt: ${prompt},
    out: ['result'],
  })`
    }
    case 'run': {
      const script = JSON.stringify(scriptPathOf(node))
      return `  const ${ident(node.id)} = await step.run(${label}, { script: ${script} })`
    }
    case 'human': {
      const prompt = JSON.stringify(node.gatePrompt || node.label)
      const fields = JSON.stringify(node.gateFields?.length ? node.gateFields : ['approved'])
      return `  const ${ident(node.id)} = await step.human(${label}, {
    prompt: ${prompt},
    fields: ${fields},
  })`
    }
    case 'call': {
      const ref = JSON.stringify((node.callRef ?? '').trim())
      return `  const ${ident(node.id)} = await step.call(${label}, ${ref}, ctx.input)`
    }
    default:
      throw new FlowCompileError(`cannot emit ${node.kind} "${node.id}" as a step`)
  }
}

function mergeOutputs(identName: string, asList = false): string {
  if (asList) {
    return `  if (Array.isArray(${identName})) {
    for (const __r of ${identName}) {
      if (__r && typeof __r === 'object' && !Array.isArray(__r)) Object.assign(__rivetOutputs, __r)
    }
  }`
  }
  return `  if (${identName} && typeof ${identName} === 'object') Object.assign(__rivetOutputs, ${identName})`
}

function emitDone(output: WorkflowField[]): string {
  const fields = (output.length > 0 ? output : defaultOutput()).filter((f) => f.required !== false)
  if (fields.length === 0) return '  await step.done({})'
  const pairs = fields.map((f) => {
    const fallback =
      f.type === 'number' ? '0' : f.type === 'boolean' ? 'true' : f.type === 'json' ? '{}' : '""'
    return `    ${JSON.stringify(f.name)}: __rivetOutputs[${JSON.stringify(f.name)}] ?? ${fallback},`
  })
  return `  await step.done({\n${pairs.join('\n')}\n  })`
}

function emitParallel(node: FlowAuthorNode, kids: FlowAuthorNode[]): string {
  if (kids.length === 0) return `  // parallel ${JSON.stringify(node.id)} has no branches`
  const branches = kids.map((kid) => {
    const body = indentLines(emitStep(kid), '    ')
    return `    async (step) => {
${body}
      return ${ident(kid.id)}
    }`
  })
  return `  const ${ident(node.id)} = await step.parallel(${JSON.stringify(node.id)}, [
${branches.join(',\n')}
  ])`
}

const PARALLEL_CHILD_KINDS = new Set(['agent', 'run', 'call'])

export function compileFlow(graph: FlowAuthorGraph, meta: CompileMeta): CompiledWorkflow {
  validateFlow(graph, meta)

  const files: Record<string, string> = {}
  const reachable = reachableFromStart(graph)
  const order = topoSort(graph)
  const skip = new Set<string>()
  const outlineNodes: FlowAuthorNode[] = []
  const doneNodes: FlowAuthorNode[] = []
  const stepLines: string[] = ['  const __rivetOutputs: Record<string, unknown> = { ...ctx.input }']
  const output = meta.output.length > 0 ? meta.output : defaultOutput()

  for (const id of order) {
    if (id === FLOW_START_ID) continue
    if (!reachable.has(id)) continue
    if (skip.has(id)) continue
    const node = nodeById(graph, id)
    if (!node) continue
    if (node.kind === 'done') {
      // Emit a single step.done after every other reachable node so a done
      // that sorts mid-order cannot drop siblings (start→a, a→done, a→b).
      doneNodes.push(node)
      continue
    }
    outlineNodes.push(node)
    if (node.kind === 'parallel') {
      const kids = outgoingIds(graph, id)
        .map((kid) => nodeById(graph, kid))
        .filter((n): n is FlowAuthorNode => Boolean(n))
      for (const k of kids) {
        if (!PARALLEL_CHILD_KINDS.has(k.kind)) {
          throw new FlowCompileError(
            `parallel "${node.id}" cannot branch to ${k.kind} "${k.id}" (agent, script, or call only)`,
          )
        }
        const incoming = incomingIds(graph, k.id)
        if (incoming.length !== 1 || incoming[0] !== node.id) {
          throw new FlowCompileError(
            `parallel child "${k.id}" must have exactly one incoming wire from "${node.id}"`,
          )
        }
        skip.add(k.id)
        outlineNodes.push(k)
      }
      stepLines.push(emitParallel(node, kids))
      if (kids.length > 0) stepLines.push(mergeOutputs(ident(node.id), true))
      continue
    }
    stepLines.push(emitStep(node))
    stepLines.push(mergeOutputs(ident(node.id)))
  }
  outlineNodes.push(...doneNodes)
  stepLines.push(emitDone(output))

  const input = meta.input.length > 0 ? meta.input : defaultInput()
  const outlineYaml = outlineNodes
    .map((n) => {
      return `  - id: ${yamlScalar(n.id)}\n    kind: ${n.kind}\n    label: ${yamlScalar(n.label)}`
    })
    .join('\n')

  let budgets = ''
  if (meta.budgets?.maxTokens !== undefined) {
    budgets += `  maxTokens: ${String(meta.budgets.maxTokens)}\n`
  }
  if (meta.budgets?.maxCost !== undefined) {
    budgets += `  maxCost: ${String(meta.budgets.maxCost)}\n`
  }
  if (meta.budgets?.maxConcurrentRuns !== undefined) {
    budgets += `  maxConcurrentRuns: ${String(meta.budgets.maxConcurrentRuns)}\n`
  }

  files['workflow.yaml'] =
    `id: ${yamlScalar(meta.id)}
version: ${yamlScalar(meta.version)}
name: ${yamlScalar(meta.name)}
description: ${yamlScalar(meta.description ?? meta.name)}
input:
${yamlFields(input, '  ')}
output:
${yamlFields(output, '  ')}
outline:
${outlineYaml || '  []'}
${budgets ? `budgets:\n${budgets}` : ''}`.trimEnd() + '\n'

  files['run.ts'] = `/** ${RUN_TS_MARKER}. Do not edit — Save from the canvas. */
import type { Step } from '@rivetos/workflows'

export default async function run(
  step: Step,
  ctx: { input: Record<string, unknown> },
): Promise<void> {
${stepLines.join('\n\n')}
}
`

  const owned = ownedFromNodes(graph.nodes, reachable)
  files[FLOWS_FILE] =
    `${JSON.stringify({ version: 1, nodes: graph.nodes, edges: graph.edges, owned }, null, 2)}\n`

  const createOnly: string[] = []
  for (const n of graph.nodes) {
    if (!reachable.has(n.id) && n.id !== FLOW_START_ID) continue
    if (n.kind === 'agent') {
      files[`agents/${agentStem(n)}.md`] = agentFile(n)
    }
    if (n.kind === 'run') {
      const path = scriptPathOf(n)
      files[path] = scriptStub(n)
      createOnly.push(path)
    }
  }

  return { files, createOnly, owned }
}

const AUTHOR_KINDS = new Set<string>(['agent', 'call', 'done', 'human', 'parallel', 'run', 'start'])

export function parseFlowsFile(text: string): FlowAuthorGraph {
  const raw: unknown = JSON.parse(text)
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    throw new Error('flows.json: expected object')
  }
  const o = raw as { nodes?: unknown; edges?: unknown }
  if (!Array.isArray(o.nodes) || !Array.isArray(o.edges)) {
    throw new Error('flows.json: nodes and edges required')
  }
  const nodes: FlowAuthorGraph['nodes'] = []
  const seenIds = new Set<string>()
  for (const item of o.nodes) {
    if (!item || typeof item !== 'object') throw new Error('flows.json: invalid node')
    const n = item as Record<string, unknown>
    if (typeof n.id !== 'string' || n.id.length === 0) throw new Error('flows.json: node.id')
    if (seenIds.has(n.id)) throw new Error(`flows.json: duplicate node id ${n.id}`)
    seenIds.add(n.id)
    if (typeof n.kind !== 'string' || !AUTHOR_KINDS.has(n.kind)) {
      throw new Error(`flows.json: bad kind on ${n.id}`)
    }
    if (typeof n.x !== 'number' || !Number.isFinite(n.x))
      throw new Error(`flows.json: node.x ${n.id}`)
    if (typeof n.y !== 'number' || !Number.isFinite(n.y))
      throw new Error(`flows.json: node.y ${n.id}`)
    if (typeof n.label !== 'string') throw new Error(`flows.json: node.label ${n.id}`)
    const node: FlowAuthorGraph['nodes'][number] = {
      id: n.id,
      kind: n.kind as FlowAuthorKind,
      label: n.label,
      x: n.x,
      y: n.y,
    }
    if (typeof n.agentName === 'string') node.agentName = n.agentName
    if (typeof n.prompt === 'string') node.prompt = n.prompt
    if (typeof n.model === 'string') node.model = n.model
    if (typeof n.maxTurns === 'number' && Number.isFinite(n.maxTurns)) node.maxTurns = n.maxTurns
    if (Array.isArray(n.tools) && n.tools.every((t) => typeof t === 'string')) {
      node.tools = n.tools
    }
    if (typeof n.scriptPath === 'string') node.scriptPath = n.scriptPath
    if (typeof n.gatePrompt === 'string') node.gatePrompt = n.gatePrompt
    if (Array.isArray(n.gateFields) && n.gateFields.every((t) => typeof t === 'string')) {
      node.gateFields = n.gateFields
    }
    if (typeof n.callRef === 'string') node.callRef = n.callRef
    nodes.push(node)
  }
  const edges: FlowAuthorGraph['edges'] = []
  for (const item of o.edges) {
    if (!item || typeof item !== 'object') throw new Error('flows.json: invalid edge')
    const e = item as Record<string, unknown>
    if (typeof e.id !== 'string' || typeof e.from !== 'string' || typeof e.to !== 'string') {
      throw new Error('flows.json: invalid edge')
    }
    if (!seenIds.has(e.from) || !seenIds.has(e.to)) {
      throw new Error(`flows.json: dangling edge ${e.id}`)
    }
    edges.push({ id: e.id, from: e.from, to: e.to })
  }
  return { nodes, edges }
}
