/**
 * Compile a flows canvas graph into the workflow directory the engine already
 * runs: workflow.yaml, run.ts, agents/*.md, scripts/*.sh, flows.json.
 */

import type { WorkflowField } from '@rivetos/types'
import {
  FLOW_START_ID,
  incomingIds,
  nodeById,
  outgoingIds,
  reachableFromStart,
  slugify,
  topoSort,
  type FlowAuthorGraph,
  type FlowAuthorNode,
} from './flow-graph.js'

export class FlowCompileError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'FlowCompileError'
  }
}

export const FLOWS_FILE = 'flows.json'
export const RUN_TS_MARKER = '@generated by RivetHub flows canvas'

export interface CompileMeta {
  id: string
  name: string
  version: string
  description?: string
  input: WorkflowField[]
  output: WorkflowField[]
  budgets?: { maxTokens?: number; maxCost?: number; maxConcurrentRuns?: number }
}

export interface CompiledWorkflow {
  files: Record<string, string>
  /** Paths that must not overwrite an existing file (script stubs). */
  createOnly: string[]
}

function ident(id: string): string {
  const s = id.replace(/[^a-zA-Z0-9_]/g, '_')
  return /^[A-Za-z_]/.test(s) ? s : `s_${s}`
}

function yamlScalar(v: string): string {
  const lower = v.toLowerCase()
  if (
    /^[A-Za-z0-9_./-]+$/.test(v) &&
    !['true', 'false', 'null', 'yes', 'no', 'on', 'off'].includes(lower)
  ) {
    return v
  }
  return JSON.stringify(v)
}

function yamlFields(fields: WorkflowField[], indent: string): string {
  if (fields.length === 0) return `${indent}[]\n`
  return fields
    .map((f) => {
      const req = f.required === true ? `\n${indent}  required: true` : ''
      const desc = f.description ? `\n${indent}  description: ${yamlScalar(f.description)}` : ''
      return `${indent}- name: ${yamlScalar(f.name)}\n${indent}  type: ${f.type}${req}${desc}`
    })
    .join('\n')
}

function defaultInput(): WorkflowField[] {
  return [{ name: 'message', type: 'string', required: true, description: 'Input message' }]
}

function defaultOutput(): WorkflowField[] {
  return [{ name: 'result', type: 'string', description: 'Final result' }]
}

function agentFile(node: FlowAuthorNode): string {
  const tools = node.tools ?? []
  const lines = ['---', `tools: [${tools.map((t) => yamlScalar(t)).join(', ')}]`]
  if (node.model) lines.push(`model: ${yamlScalar(node.model)}`)
  if (node.maxTurns !== undefined) lines.push(`maxTurns: ${String(node.maxTurns)}`)
  lines.push('---', '', node.prompt?.trim() || 'You are a workflow agent.', '')
  return lines.join('\n')
}

function scriptStub(node: FlowAuthorNode): string {
  return `#!/bin/sh
set -eu
# Deterministic step "${node.label}" — no model, no tokens.
# Case directory is the working directory for this run.
echo "ok"
`
}

function emitStep(node: FlowAuthorNode): string {
  const label = JSON.stringify(node.id)
  switch (node.kind) {
    case 'agent': {
      const agent = JSON.stringify(node.agentName || slugify(node.label) || node.id)
      return `  const ${ident(node.id)} = await step.agent(${label}, {
    agent: ${agent},
    prompt: ${JSON.stringify(node.label)},
    out: ['result'],
  })`
    }
    case 'run': {
      const script = JSON.stringify(node.scriptPath || `scripts/${node.id}.sh`)
      return `  const ${ident(node.id)} = await step.run(${label}, { script: ${script} })`
    }
    case 'human': {
      const prompt = JSON.stringify(node.gatePrompt || node.label)
      const fields = JSON.stringify(node.gateFields?.length ? node.gateFields : ['approved'])
      return `  const ${ident(node.id)} = await step.human(${label}, {
    prompt: ${prompt},
    fields: ${fields},
  })`
    }
    case 'call': {
      const ref = JSON.stringify(node.callRef || node.label)
      return `  const ${ident(node.id)} = await step.call(${label}, ${ref}, ctx.input)`
    }
    default:
      throw new FlowCompileError(`cannot emit ${node.kind} "${node.id}" as a step`)
  }
}

function emitDone(output: WorkflowField[]): string {
  const fields = (output.length > 0 ? output : defaultOutput()).filter((f) => f.required !== false)
  if (fields.length === 0) return '  await step.done({})'
  const pairs = fields.map((f) => {
    const fallback =
      f.type === 'number' ? '0' : f.type === 'boolean' ? 'true' : f.type === 'json' ? '{}' : '""'
    return `    ${JSON.stringify(f.name)}: ctx.input[${JSON.stringify(f.name)}] ?? ${fallback},`
  })
  return `  await step.done({\n${pairs.join('\n')}\n  })`
}

function emitParallel(node: FlowAuthorNode, kids: FlowAuthorNode[]): string {
  if (kids.length === 0) return `  // parallel ${JSON.stringify(node.id)} has no branches`
  const branches = kids.map((kid) => {
    const body = emitStep(kid).replace(/^\s+/, '      ')
    return `    async (step) => {
${body}
      return ${ident(kid.id)}
    }`
  })
  return `  await step.parallel(${JSON.stringify(node.id)}, [
${branches.join(',\n')}
  ])`
}

const PARALLEL_CHILD_KINDS = new Set(['agent', 'run', 'call'])

export function compileFlow(graph: FlowAuthorGraph, meta: CompileMeta): CompiledWorkflow {
  const files: Record<string, string> = {}
  const reachable = reachableFromStart(graph)
  const order = topoSort(graph)
  const skip = new Set<string>()
  const outlineNodes: FlowAuthorNode[] = []
  const stepLines: string[] = []
  let emittedDone = false
  const output = meta.output.length > 0 ? meta.output : defaultOutput()

  for (const id of order) {
    if (id === FLOW_START_ID) continue
    if (!reachable.has(id)) continue
    if (skip.has(id)) continue
    const node = nodeById(graph, id)
    if (!node) continue
    outlineNodes.push(node)
    if (node.kind === 'parallel') {
      const kids = outgoingIds(graph, id)
        .map((kid) => nodeById(graph, kid))
        .filter((n): n is FlowAuthorNode => Boolean(n))
      for (const k of kids) {
        if (!PARALLEL_CHILD_KINDS.has(k.kind)) {
          throw new FlowCompileError(
            `parallel "${node.id}" cannot branch to ${k.kind} "${k.id}" (agent, script, or call only)`,
          )
        }
        const incoming = incomingIds(graph, k.id)
        if (incoming.length !== 1 || incoming[0] !== node.id) {
          throw new FlowCompileError(
            `parallel child "${k.id}" must have exactly one incoming wire from "${node.id}"`,
          )
        }
        skip.add(k.id)
        outlineNodes.push(k)
      }
      stepLines.push(emitParallel(node, kids))
      continue
    }
    if (node.kind === 'done') {
      stepLines.push(emitDone(output))
      emittedDone = true
      break
    }
    stepLines.push(emitStep(node))
  }
  if (!emittedDone) stepLines.push(emitDone(output))

  const input = meta.input.length > 0 ? meta.input : defaultInput()
  const outlineYaml = outlineNodes
    .map((n) => {
      return `  - id: ${yamlScalar(n.id)}\n    kind: ${n.kind}\n    label: ${yamlScalar(n.label)}`
    })
    .join('\n')

  let budgets = ''
  if (meta.budgets?.maxTokens !== undefined) {
    budgets += `  maxTokens: ${String(meta.budgets.maxTokens)}\n`
  }
  if (meta.budgets?.maxCost !== undefined) {
    budgets += `  maxCost: ${String(meta.budgets.maxCost)}\n`
  }
  if (meta.budgets?.maxConcurrentRuns !== undefined) {
    budgets += `  maxConcurrentRuns: ${String(meta.budgets.maxConcurrentRuns)}\n`
  }

  files['workflow.yaml'] =
    `id: ${yamlScalar(meta.id)}
version: ${yamlScalar(meta.version)}
name: ${yamlScalar(meta.name)}
description: ${yamlScalar(meta.description ?? meta.name)}
input:
${yamlFields(input, '  ')}
output:
${yamlFields(output, '  ')}
outline:
${outlineYaml || '  []'}
${budgets ? `budgets:\n${budgets}` : ''}`.trimEnd() + '\n'

  files['run.ts'] = `/** ${RUN_TS_MARKER}. Do not edit — Save from the canvas. */
import type { Step } from '@rivetos/workflows'

export default async function run(
  step: Step,
  ctx: { input: Record<string, unknown> },
): Promise<void> {
  void ctx
${stepLines.join('\n\n')}
}
`

  files[FLOWS_FILE] =
    `${JSON.stringify({ version: 1, nodes: graph.nodes, edges: graph.edges }, null, 2)}\n`

  const createOnly: string[] = []
  const agentStems = new Map<string, string>()
  for (const n of graph.nodes) {
    if (!reachable.has(n.id) && n.id !== FLOW_START_ID) continue
    if (n.kind === 'agent') {
      const stem = n.agentName || slugify(n.label) || n.id
      const prev = agentStems.get(stem)
      if (prev && prev !== n.id) {
        throw new FlowCompileError(`two agents share agents/${stem}.md ("${prev}" and "${n.id}")`)
      }
      agentStems.set(stem, n.id)
      files[`agents/${stem}.md`] = agentFile(n)
    }
    if (n.kind === 'run') {
      const path = n.scriptPath || `scripts/${n.id}.sh`
      files[path] = scriptStub(n)
      createOnly.push(path)
    }
  }

  return { files, createOnly }
}

const AUTHOR_KINDS = new Set(['agent', 'call', 'done', 'human', 'parallel', 'run', 'start'])

export function parseFlowsFile(text: string): FlowAuthorGraph {
  const raw: unknown = JSON.parse(text)
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    throw new Error('flows.json: expected object')
  }
  const o = raw as { nodes?: unknown; edges?: unknown }
  if (!Array.isArray(o.nodes) || !Array.isArray(o.edges)) {
    throw new Error('flows.json: nodes and edges required')
  }
  const nodes: FlowAuthorGraph['nodes'] = []
  for (const item of o.nodes) {
    if (!item || typeof item !== 'object') throw new Error('flows.json: invalid node')
    const n = item as Record<string, unknown>
    if (typeof n.id !== 'string' || n.id.length === 0) throw new Error('flows.json: node.id')
    if (typeof n.kind !== 'string' || !AUTHOR_KINDS.has(n.kind)) {
      throw new Error(`flows.json: bad kind on ${n.id}`)
    }
    if (typeof n.x !== 'number' || !Number.isFinite(n.x))
      throw new Error(`flows.json: node.x ${n.id}`)
    if (typeof n.y !== 'number' || !Number.isFinite(n.y))
      throw new Error(`flows.json: node.y ${n.id}`)
    if (typeof n.label !== 'string') throw new Error(`flows.json: node.label ${n.id}`)
    nodes.push(n as FlowAuthorGraph['nodes'][number])
  }
  const edges: FlowAuthorGraph['edges'] = []
  for (const item of o.edges) {
    if (!item || typeof item !== 'object') throw new Error('flows.json: invalid edge')
    const e = item as Record<string, unknown>
    if (typeof e.id !== 'string' || typeof e.from !== 'string' || typeof e.to !== 'string') {
      throw new Error('flows.json: invalid edge')
    }
    edges.push({ id: e.id, from: e.from, to: e.to })
  }
  return { nodes, edges }
}
