/**
 * Config generation — converts wizard state into config.yaml + .env files.
 *
 * Secrets (API keys, bot tokens, DB passwords) go into .env only.
 * The YAML config references them via environment variable names.
 */

import { writeFile, mkdir, access, readFile, readdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { stringify as toYaml } from 'yaml'
import { ENROLL_SNIPPET_MARKER } from '../../lib/mesh-enroll.js'
import type { WizardState, WizardAgent } from './types.js'
import { PROVIDER_ENV_KEYS } from './agents.js'

export { meshSectionFromEnroll } from '../../lib/mesh-enroll.js'

// ──────────────────────────────────────────────────────────────────────────────
// Public API
// ──────────────────────────────────────────────────────────────────────────────

export interface GenerateResult {
  configPath: string
  envPath: string
  workspacePath: string
}

export async function generateConfig(
  state: WizardState,
  rivetDir: string,
): Promise<GenerateResult> {
  const configPath = resolve(rivetDir, 'config.yaml')
  const envPath = resolve(rivetDir, '.env')
  const workspacePath = resolve(rivetDir, 'workspace')

  await mkdir(rivetDir, { recursive: true })
  await mkdir(workspacePath, { recursive: true })
  await mkdir(resolve(workspacePath, 'memory'), { recursive: true })

  // Generate config.yaml (no secrets)
  const configYaml = buildConfigYaml(state)
  await writeFile(configPath, configYaml, 'utf-8')

  // Generate .env (secrets only, append if exists)
  const envContent = buildEnvFile(state)
  await writeEnvFile(envPath, envContent)

  // Generate workspace template files
  await writeWorkspaceTemplates(workspacePath)

  return { configPath, envPath, workspacePath }
}

// ──────────────────────────────────────────────────────────────────────────────
// Config YAML builder
// ──────────────────────────────────────────────────────────────────────────────

export function buildConfigYaml(state: WizardState): string {
  const config: Record<string, unknown> = {}

  // Runtime
  config.runtime = {
    workspace: '~/.rivetos/workspace',
    default_agent: state.agents[0]?.name ?? 'rivet',
    turn_timeout: 900,
  }

  // Agents
  const agents: Record<string, Record<string, unknown>> = {}
  for (const agent of state.agents) {
    const entry: Record<string, unknown> = {
      provider: agent.provider,
    }
    if (agent.thinking !== 'off') {
      entry.default_thinking = agent.thinking
    }
    agents[agent.name] = entry
  }
  config.agents = agents

  // Providers — deduplicated by provider name
  const providers: Record<string, Record<string, unknown>> = {}
  const seen = new Set<string>()
  for (const agent of state.agents) {
    if (seen.has(agent.provider)) continue
    seen.add(agent.provider)
    providers[agent.provider] = buildProviderConfig(agent)
  }
  config.providers = providers

  // Channels: social bots removed in Phase 5. Human UX is RivetHub.
  if (state.meshSection) {
    config.mesh = state.meshSection
  }

  // Memory
  config.memory = {
    postgres: {
      // connection_string via env: RIVETOS_PG_URL
    },
  }

  // Deployment (only for docker/proxmox)
  if (state.deployment !== 'manual') {
    config.deployment = buildDeploymentConfig(state)
  }

  // Build YAML with header comment
  const header = [
    '# RivetOS Configuration',
    '# Generated by rivetos init',
    '# API keys and tokens are stored in .env — never in this file.',
    '',
  ].join('\n')

  let body = toYaml(config, {
    lineWidth: 120,
    defaultKeyType: 'PLAIN',
    defaultStringType: 'PLAIN',
  })
  // Same marker the CLI merge path keys on, so a later `mesh enroll`/`renew`
  // is a no-op instead of appending a second `mesh:` block.
  if (state.meshSection) {
    body = body.replace(
      /^mesh:/m,
      `${ENROLL_SNIPPET_MARKER}. Merge into the node's rivet.config.yaml.\nmesh:`,
    )
  }

  return header + body
}

function buildProviderConfig(agent: WizardAgent): Record<string, unknown> {
  const config: Record<string, unknown> = {
    model: agent.model,
  }

  // claude-cli doesn't accept max_tokens — the CLI binary owns generation params.
  // Every other provider gets the default cap.
  if (agent.provider !== 'claude-cli') {
    config.max_tokens = 8192
  }

  if (agent.baseUrl) {
    config.base_url = agent.baseUrl
  }

  return config
}

function buildDeploymentConfig(state: WizardState): Record<string, unknown> {
  // Only `target` is read anywhere at runtime; nested keys were write-only.
  return { target: state.deployment }
}

// ──────────────────────────────────────────────────────────────────────────────
// .env file builder
// ──────────────────────────────────────────────────────────────────────────────

interface EnvEntry {
  key: string
  value: string
  comment?: string
}

function buildEnvFile(state: WizardState): EnvEntry[] {
  const entries: EnvEntry[] = []

  // Provider API keys
  const seenProviders = new Set<string>()
  for (const agent of state.agents) {
    if (seenProviders.has(agent.provider)) continue
    seenProviders.add(agent.provider)

    if (agent.apiKey) {
      const envKey = PROVIDER_ENV_KEYS[agent.provider]
      if (envKey) {
        entries.push({ key: envKey, value: agent.apiKey, comment: `${agent.provider} provider` })
      }
    }
  }

  // Postgres
  const pgPass = state.postgresPassword
  if (state.deployment === 'manual') {
    // BYO postgres — the user supplied the connection string directly.
    if (state.postgresUrl) {
      entries.push({
        key: 'RIVETOS_PG_URL',
        value: state.postgresUrl,
        comment: 'Postgres connection (agents use this)',
      })
    }
  } else {
    // Docker / Proxmox deployments ship a bundled datahub container. The
    // hostname `datahub` is resolved on the deployment-managed network.
    entries.push({
      key: 'POSTGRES_PASSWORD',
      value: pgPass,
      comment: 'Datahub postgres password',
    })
    entries.push({
      key: 'RIVETOS_PG_URL',
      value: `postgresql://rivetos:${pgPass}@datahub:5432/rivetos`,
      comment: 'Postgres connection (agents use this)',
    })
  }

  return entries
}

async function writeEnvFile(envPath: string, entries: EnvEntry[]): Promise<void> {
  // Read existing .env to avoid duplicating keys
  let existing = ''
  try {
    existing = await readFile(envPath, 'utf-8')
  } catch {
    // File doesn't exist — that's fine
  }

  const existingKeys = new Set(
    existing
      .split('\n')
      .filter((line) => line.includes('=') && !line.startsWith('#'))
      .map((line) => line.split('=')[0].trim()),
  )

  const lines: string[] = []

  if (!existing) {
    lines.push('# RivetOS Environment — secrets and credentials')
    lines.push('# Generated by rivetos init — DO NOT commit this file.')
    lines.push('')
  }

  let addedAny = false
  for (const entry of entries) {
    if (existingKeys.has(entry.key)) continue
    if (entry.comment) lines.push(`# ${entry.comment}`)
    lines.push(`${entry.key}=${entry.value}`)
    lines.push('')
    addedAny = true
  }

  if (addedAny) {
    const content = existing ? existing.trimEnd() + '\n\n' + lines.join('\n') : lines.join('\n')
    await writeFile(envPath, content, 'utf-8')
  } else if (!existing) {
    await writeFile(envPath, lines.join('\n'), 'utf-8')
  }
}

// ──────────────────────────────────────────────────────────────────────────────
// Workspace templates
//
// Canonical template files live in `workspace-templates/` at the repo root.
// Init seeds AGENT.md, MEMORY.md, and users/, then generates CLAUDE.md from
// AGENT.md. The inline `FALLBACK_TEMPLATES` below are used only if the
// `workspace-templates/` directory cannot be located (e.g. if the CLI is
// running from an unusual install layout); they are intentionally minimal
// and should not be relied on.
// ──────────────────────────────────────────────────────────────────────────────

/**
 * Locate the `workspace-templates/` directory.
 *
 * Two layouts to support:
 *
 *   1. Source checkout (dev):
 *      <repo-root>/
 *        workspace-templates/          ← target
 *        packages/cli/
 *          src/commands/init/          ← src path
 *          dist/commands/init/         ← built path
 *
 *   2. Global npm install:
 *      <prefix>/lib/node_modules/@rivetos/cli/
 *        workspace-templates/          ← target (shipped via prepublish copy)
 *        dist/commands/init/           ← built path
 *
 * Strategy: walk up from this file's dir, try each candidate. The first hit
 * wins. Source checkout matches at depth 5; npm install matches at depth 3.
 */
async function findTemplatesDir(): Promise<string | null> {
  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition -- dirname may be undefined in older Node
  const here = import.meta.dirname ?? '.'
  for (let up = 2; up <= 6; up++) {
    const candidate = resolve(here, ...Array<string>(up).fill('..'), 'workspace-templates')
    try {
      await access(candidate)
      return candidate
    } catch {
      // try next depth
    }
  }
  return null
}

const SEEDED_MD = ['AGENT.md', 'MEMORY.md'] as const

const CLAUDE_MD_BANNER =
  '<!-- generated from AGENT.md by rivetos init — edit AGENT.md instead -->'

const FALLBACK_TEMPLATES: Record<string, string> = {
  'AGENT.md': `# AGENT.md

Define who you are — identity, operating contract, and who you serve.
This is the first file your agent reads every session.

When you don't have context on something, **search memory first**. See MEMORY.md.
`,
  'MEMORY.md': `# MEMORY.md — Context Index

Lightweight index into the memory system. Run the referenced queries
to pull context on demand, rather than dumping everything here.

Every past conversation with your human is searchable via \`memory_search\`.
When you need context on a topic, query it.
`,
  'users/profiles.json': `{
  "_owner": "",
  "_comment": "Shape: flat { string: string } map. Reserved keys start with _. Routed user ids never start with _. _owner = the node owner's user id. Non-_ keys map user ids to profile basenames (users/<profile>.md)."
}
`,
  'users/USER-TEMPLATE.md': `# USER — <id>

Replace \`<id>\` in the heading with the real user id. Then set/create
\`"<id>": "<id>"\` in \`users/profiles.json\`.
`,
}

async function writeIfMissing(filePath: string, content: string): Promise<void> {
  try {
    await access(filePath)
    return
  } catch {
    // missing — write
  }
  await mkdir(dirname(filePath), { recursive: true })
  await writeFile(filePath, content, 'utf-8')
}

async function copyIfMissing(srcPath: string, destPath: string): Promise<void> {
  try {
    await access(destPath)
    return
  } catch {
    // missing — copy
  }
  try {
    const content = await readFile(srcPath, 'utf-8')
    await mkdir(dirname(destPath), { recursive: true })
    await writeFile(destPath, content, 'utf-8')
  } catch {
    // source missing — tolerate
  }
}

async function seedUsersDir(templatesDir: string | null, workspacePath: string): Promise<void> {
  const destDir = resolve(workspacePath, 'users')
  await mkdir(destDir, { recursive: true })

  if (templatesDir) {
    const srcDir = resolve(templatesDir, 'users')
    let entries: string[] = []
    try {
      entries = await readdir(srcDir)
    } catch {
      entries = []
    }
    for (const name of entries) {
      await copyIfMissing(resolve(srcDir, name), resolve(destDir, name))
    }
    return
  }

  for (const [name, content] of Object.entries(FALLBACK_TEMPLATES)) {
    if (!name.startsWith('users/')) continue
    await writeIfMissing(resolve(workspacePath, name), content)
  }
}

async function writeClaudeMdFromAgent(workspacePath: string): Promise<void> {
  const claudePath = resolve(workspacePath, 'CLAUDE.md')
  try {
    await access(claudePath)
    return
  } catch {
    // missing — generate
  }
  let agentContent: string
  try {
    agentContent = await readFile(resolve(workspacePath, 'AGENT.md'), 'utf-8')
  } catch {
    return
  }
  await writeFile(claudePath, `${CLAUDE_MD_BANNER}\n${agentContent}`, 'utf-8')
}

async function writeWorkspaceTemplates(workspacePath: string): Promise<void> {
  const templatesDir = await findTemplatesDir()

  if (templatesDir) {
    for (const name of SEEDED_MD) {
      await copyIfMissing(resolve(templatesDir, name), resolve(workspacePath, name))
    }
  } else {
    // Fallback path — use the minimal inline templates. This should only
    // trigger if the CLI is installed without the repo's workspace-templates
    // directory alongside it.
    for (const name of SEEDED_MD) {
      const content = FALLBACK_TEMPLATES[name]
      if (content) await writeIfMissing(resolve(workspacePath, name), content)
    }
  }

  await seedUsersDir(templatesDir, workspacePath)
  await writeClaudeMdFromAgent(workspacePath)
}
