/**
 * Config generation — converts wizard state into config.yaml + .env files.
 *
 * Secrets (API keys, bot tokens, DB passwords) go into .env only.
 * The YAML config references them via environment variable names.
 */

import { writeFile, mkdir, access, readFile } from 'node:fs/promises'
import { resolve, dirname } from 'node:path'
import { stringify as toYaml } from 'yaml'
import type { WizardState, WizardAgent, WizardChannel } from './types.js'
import { PROVIDER_ENV_KEYS } from './agents.js'

// ──────────────────────────────────────────────────────────────────────────────
// Public API
// ──────────────────────────────────────────────────────────────────────────────

export interface GenerateResult {
  configPath: string
  envPath: string
  workspacePath: string
}

export async function generateConfig(
  state: WizardState,
  rivetDir: string,
): Promise<GenerateResult> {
  const configPath = resolve(rivetDir, 'config.yaml')
  const envPath = resolve(rivetDir, '.env')
  const workspacePath = resolve(rivetDir, 'workspace')

  await mkdir(rivetDir, { recursive: true })
  await mkdir(workspacePath, { recursive: true })
  await mkdir(resolve(workspacePath, 'memory'), { recursive: true })

  // Generate config.yaml (no secrets)
  const configYaml = buildConfigYaml(state)
  await writeFile(configPath, configYaml, 'utf-8')

  // Generate .env (secrets only, append if exists)
  const envContent = buildEnvFile(state)
  await writeEnvFile(envPath, envContent)

  // Generate workspace template files
  await writeWorkspaceTemplates(workspacePath)

  return { configPath, envPath, workspacePath }
}

// ──────────────────────────────────────────────────────────────────────────────
// Config YAML builder
// ──────────────────────────────────────────────────────────────────────────────

function buildConfigYaml(state: WizardState): string {
  const config: Record<string, unknown> = {}

  // Runtime
  config.runtime = {
    workspace: '~/.rivetos/workspace',
    default_agent: state.agents[0]?.name ?? 'rivet',
    turn_timeout: 600,
  }

  // Agents
  const agents: Record<string, Record<string, unknown>> = {}
  for (const agent of state.agents) {
    const entry: Record<string, unknown> = {
      provider: agent.provider,
    }
    if (agent.thinking !== 'off') {
      entry.default_thinking = agent.thinking
    }
    agents[agent.name] = entry
  }
  config.agents = agents

  // Providers — deduplicated by provider name
  const providers: Record<string, Record<string, unknown>> = {}
  const seen = new Set<string>()
  for (const agent of state.agents) {
    if (seen.has(agent.provider)) continue
    seen.add(agent.provider)
    providers[agent.provider] = buildProviderConfig(agent)
  }
  config.providers = providers

  // Channels
  if (state.channels.length > 0) {
    const channels: Record<string, Record<string, unknown>> = {}
    for (const ch of state.channels) {
      channels[ch.type] = buildChannelConfig(ch)
    }
    config.channels = channels
  }

  // Memory
  config.memory = {
    postgres: {
      // connection_string via env: RIVETOS_PG_URL
    },
  }

  // Deployment (only for docker/proxmox)
  if (state.deployment !== 'manual') {
    config.deployment = buildDeploymentConfig(state)
  }

  // Build YAML with header comment
  const header = [
    '# RivetOS Configuration',
    '# Generated by rivetos init',
    '# API keys and tokens are stored in .env — never in this file.',
    '',
  ].join('\n')

  return (
    header +
    toYaml(config, {
      lineWidth: 120,
      defaultKeyType: 'PLAIN',
      defaultStringType: 'PLAIN',
    })
  )
}

function buildProviderConfig(agent: WizardAgent): Record<string, unknown> {
  const config: Record<string, unknown> = {
    model: agent.model,
    max_tokens: 8192,
  }

  if (agent.baseUrl) {
    config.base_url = agent.baseUrl
  }

  return config
}

function buildChannelConfig(channel: WizardChannel): Record<string, unknown> {
  const config: Record<string, unknown> = {
    owner_id: channel.ownerId,
  }

  if (channel.type === 'telegram') {
    config.allowed_users = [channel.ownerId]
  }

  if (channel.type === 'discord') {
    config.channel_bindings = {}
  }

  return config
}

function buildDeploymentConfig(state: WizardState): Record<string, unknown> {
  const deployment: Record<string, unknown> = {
    target: state.deployment,
    datahub: {
      postgres: true,
      shared_storage: true,
      shared_mount_path: '/shared',
    },
    image: {
      build_from_source: true,
    },
  }

  if (state.deployment === 'docker') {
    deployment.docker = {
      network: 'rivetos-net',
      postgres_port: 5432,
    }
  }

  if (state.deployment === 'proxmox' && state.proxmox) {
    deployment.proxmox = {
      api_url: state.proxmox.apiUrl,
      nodes: state.proxmox.nodes.map((n) => ({
        name: n.name,
        host: n.host,
        role: n.role,
      })),
      network: state.proxmox.network,
    }
  }

  return deployment
}

// ──────────────────────────────────────────────────────────────────────────────
// .env file builder
// ──────────────────────────────────────────────────────────────────────────────

interface EnvEntry {
  key: string
  value: string
  comment?: string
}

function buildEnvFile(state: WizardState): EnvEntry[] {
  const entries: EnvEntry[] = []

  // Provider API keys
  const seenProviders = new Set<string>()
  for (const agent of state.agents) {
    if (seenProviders.has(agent.provider)) continue
    seenProviders.add(agent.provider)

    if (agent.apiKey) {
      const envKey = PROVIDER_ENV_KEYS[agent.provider]
      if (envKey) {
        entries.push({ key: envKey, value: agent.apiKey, comment: `${agent.provider} provider` })
      } else if (agent.provider === 'openai-compat') {
        entries.push({
          key: 'OPENAI_API_KEY',
          value: agent.apiKey,
          comment: 'OpenAI-compatible provider',
        })
      }
    }
  }

  // Channel tokens
  for (const ch of state.channels) {
    if (ch.type === 'discord') {
      entries.push({ key: 'DISCORD_BOT_TOKEN', value: ch.botToken, comment: 'Discord bot' })
    } else {
      entries.push({ key: 'TELEGRAM_BOT_TOKEN', value: ch.botToken, comment: 'Telegram bot' })
    }
  }

  // Postgres
  const pgPass = state.postgresPassword
  entries.push({
    key: 'POSTGRES_PASSWORD',
    value: pgPass,
    comment: 'Datahub postgres password',
  })
  entries.push({
    key: 'RIVETOS_PG_URL',
    value: `postgresql://rivetos:${pgPass}@datahub:5432/rivetos`,
    comment: 'Postgres connection (agents use this)',
  })

  return entries
}

async function writeEnvFile(envPath: string, entries: EnvEntry[]): Promise<void> {
  // Read existing .env to avoid duplicating keys
  let existing = ''
  try {
    existing = await readFile(envPath, 'utf-8')
  } catch {
    // File doesn't exist — that's fine
  }

  const existingKeys = new Set(
    existing
      .split('\n')
      .filter((line) => line.includes('=') && !line.startsWith('#'))
      .map((line) => line.split('=')[0].trim()),
  )

  const lines: string[] = []

  if (!existing) {
    lines.push('# RivetOS Environment — secrets and credentials')
    lines.push('# Generated by rivetos init — DO NOT commit this file.')
    lines.push('')
  }

  let addedAny = false
  for (const entry of entries) {
    if (existingKeys.has(entry.key)) continue
    if (entry.comment) lines.push(`# ${entry.comment}`)
    lines.push(`${entry.key}=${entry.value}`)
    lines.push('')
    addedAny = true
  }

  if (addedAny) {
    const content = existing ? existing.trimEnd() + '\n\n' + lines.join('\n') : lines.join('\n')
    await writeFile(envPath, content, 'utf-8')
  } else if (!existing) {
    await writeFile(envPath, lines.join('\n'), 'utf-8')
  }
}

// ──────────────────────────────────────────────────────────────────────────────
// Workspace templates
// ──────────────────────────────────────────────────────────────────────────────

const TEMPLATES: Record<string, string> = {
  'CORE.md': `# CORE.md

Define who you are — identity, personality, and operating values.
This is the first file your agent reads every session.

## Be Resourceful

When you don't have context on something, **search memory first**. Every
conversation you've ever had with your human is stored and searchable via
\`memory_search\`. Odds are you've already talked about it. Don't make your
human re-explain things — query memory, then ask if you're still stuck.
`,
  'USER.md': `# USER.md

About your human — name, preferences, work style, and context
your agent needs to work effectively with you.
`,
  'WORKSPACE.md': `# WORKSPACE.md — Operating Rules

This folder is home. Treat it that way.

## 🔩 Where You Are — RivetOS

You're running inside **RivetOS** — an agent runtime. This isn't a generic
chatbot shell; it's your operating system.

- **Source:** \`github.com/philbert440/rivetOS\`
- **You may be one of several agents** sharing this runtime (different
  models, same identity, same memory, same workspace files). Check
  \`config.yaml\` to see who else is configured.
- **Tools** are provided by the runtime: \`shell\`, \`file_*\`, \`search_*\`,
  \`web_*\`, \`memory_*\`, \`subagent_*\`, \`coding_pipeline\`, plus any skills
  you've loaded. See \`CAPABILITIES.md\` for the full inventory.
- **Memory is persistent across sessions.** Every conversation you've ever
  had with your human is stored and searchable via \`memory_search\`,
  \`memory_browse\`, and \`memory_stats\`. When you wake up fresh and don't
  have context on something — **search memory first.** Odds are you've
  already discussed it.

**When in doubt, search memory.** Don't guess, don't ask your human to
re-explain. Query it.

## Every Session

Before doing anything else:

1. Read \`CORE.md\` — this is who you are
2. Read \`USER.md\` — this is who you're helping
3. Read \`WORKSPACE.md\` — this is how we operate
4. Read \`MEMORY.md\` — lightweight index, query what you need
5. Read \`memory/YYYY-MM-DD.md\` (today + yesterday) for recent context

Don't ask permission. Just do it.

## Memory

You wake up fresh each session. These files are your continuity:

- **Daily notes:** \`memory/YYYY-MM-DD.md\` — raw logs of what happened
- **Memory index:** \`MEMORY.md\` — lightweight reference pointing at
  searches you can run on demand

Capture what matters. Decisions, context, things to remember.

### 📝 Write It Down — No "Mental Notes"

- **Memory is limited** — if you want to remember something, WRITE IT DOWN
- "Mental notes" don't survive session restarts. Files do.
- When your human says "remember this" → update \`memory/YYYY-MM-DD.md\`
- When you learn a lesson → update the relevant workspace file or skill
- **Text > Brain** 📝

## 🗂️ Project Continuity — AGENT.md Files

When you're working on a project with your human, **keep a live context
file at the project root** so any agent (future you, or a different model)
can pick up exactly where you left off.

**Convention:** Each active project gets an \`AGENT.md\` containing:

- **Current state** — what's done, what's in progress, what's next
- **Key decisions** — why things are the way they are
- **Open questions** — things waiting on your human
- **Gotchas** — traps you already stepped in, don't repeat

**Update it as you go**, not just at the end. If you get rate-limited,
cut off, or another agent takes over mid-task, the next session should be
able to read \`AGENT.md\` and continue without interrupting your human.

**Rule of thumb:** If your human had to ask "what were we doing?", the
file wasn't doing its job.

## Safety

- Don't exfiltrate private data. Ever.
- Don't run destructive commands without asking.
- \`trash\` > \`rm\` (recoverable beats gone forever)
- When in doubt, ask.

## External vs Internal

**Safe to do freely:**

- Read files, explore, organize, learn
- Search memory and the web
- Work within this workspace

**Ask first:**

- Sending emails, messages, public posts
- Anything that leaves the machine
- Anything you're uncertain about

## Make It Yours

This is a starting point. Add your own conventions, style, and rules as
you figure out what works.
`,
  'MEMORY.md': `# MEMORY.md — Context Index

Lightweight index into the memory system. Run the referenced queries
to pull context on demand, rather than dumping everything here.

Every past conversation with your human is searchable via \`memory_search\`.
When you need context on a topic, query it.

## Active Projects

| Project | Query | Notes |
|---------|-------|-------|
| _(add projects as they come up)_ | \`memory_search("project name status")\` | |

## Key Decisions

| Decision | Query |
|----------|-------|
| _(add as they're made)_ | \`memory_search("decision topic")\` |

## Lessons Learned

| Lesson | Query |
|--------|-------|
| _(add as you learn them)_ | \`memory_search("lesson topic")\` |
`,
  'CAPABILITIES.md': `# CAPABILITIES.md

Tools, skills, and infrastructure reference. Lists what your
agent can do and how to access external services.
`,
}

async function writeWorkspaceTemplates(workspacePath: string): Promise<void> {
  for (const [name, content] of Object.entries(TEMPLATES)) {
    const filePath = resolve(workspacePath, name)
    try {
      await access(filePath)
      // File exists — don't overwrite
    } catch {
      await writeFile(filePath, content, 'utf-8')
    }
  }
}

// ──────────────────────────────────────────────────────────────────────────────
// State persistence (for resumable init)
// ──────────────────────────────────────────────────────────────────────────────

const STATE_FILE = '.rivetos-init-state.json'

export async function saveWizardState(state: WizardState, rivetDir: string): Promise<void> {
  const statePath = resolve(dirname(rivetDir), STATE_FILE)
  // Strip secrets before saving state
  const safe = {
    ...state,
    agents: state.agents.map((a) => ({ ...a, apiKey: undefined })),
    channels: state.channels.map((c) => ({ ...c, botToken: '***' })),
    postgresPassword: '***',
  }
  await writeFile(statePath, JSON.stringify(safe, null, 2), 'utf-8')
}

export async function loadWizardState(rivetDir: string): Promise<Partial<WizardState> | null> {
  const statePath = resolve(dirname(rivetDir), STATE_FILE)
  try {
    const raw = await readFile(statePath, 'utf-8')
    return JSON.parse(raw) as Partial<WizardState>
  } catch {
    return null
  }
}

export async function clearWizardState(rivetDir: string): Promise<void> {
  const statePath = resolve(dirname(rivetDir), STATE_FILE)
  const { unlink } = await import('node:fs/promises')
  try {
    await unlink(statePath)
  } catch {
    // Doesn't exist — that's fine
  }
}
