import { describe, it, expect, vi, beforeEach } from 'vitest'

// Mock the SSH layer — these tests exercise the den deploy stage's control
// flow, not real SSH (mirrors remote-nodes.test.ts).
vi.mock('../../lib/ssh.js', async (importOriginal) => {
  const real = await importOriginal<typeof import('../../lib/ssh.js')>()
  return {
    ...real,
    sshExec: vi.fn(),
    sshExecQuiet: vi.fn(),
  }
})

import { sshExec, sshExecQuiet } from '../../lib/ssh.js'
import {
  parseDenSettings,
  buildDenEnvContent,
  denProbeHost,
  deployDenRemote,
} from './den-deploy.js'

const sshExecMock = vi.mocked(sshExec)
const sshExecQuietMock = vi.mocked(sshExecQuiet)

const ROOT = '/opt/rivetos'

const DEN_YAML = `
runtime:
  workspace: ~/.rivetos/workspace
  default_agent: opus
den:
  enabled: true
  host: 0.0.0.0
  port: 5175
  token: den-secret
  terminal:
    enabled: true
  static_dir: /srv/den/dist
`

beforeEach(() => {
  vi.clearAllMocks()
  vi.spyOn(console, 'log').mockImplementation(() => undefined)
  vi.spyOn(console, 'warn').mockImplementation(() => undefined)
  vi.spyOn(console, 'error').mockImplementation(() => undefined)
})

// ---------------------------------------------------------------------------
// parseDenSettings
// ---------------------------------------------------------------------------

describe('parseDenSettings', () => {
  it('is disabled with sensible defaults when there is no config at all', () => {
    const s = parseDenSettings(null, ROOT)
    expect(s.enabled).toBe(false)
    expect(s.host).toBe('127.0.0.1')
    expect(s.port).toBe(5174)
    expect(s.token).toBe('')
    expect(s.termEnabled).toBe(false)
  })

  it('is disabled when the config has no den section', () => {
    const s = parseDenSettings('runtime:\n  workspace: /tmp\n', ROOT)
    expect(s.enabled).toBe(false)
  })

  it('is disabled on unparseable YAML (deploy stage must never throw)', () => {
    const s = parseDenSettings('runtime: [unclosed', ROOT)
    expect(s.enabled).toBe(false)
  })

  it('derives static/packs dirs from the install root by default', () => {
    const s = parseDenSettings('den:\n  enabled: true\n', ROOT)
    expect(s.staticDir).toBe('/opt/rivetos/apps/den/dist')
    expect(s.packsDir).toBe('/opt/rivetos/packages/den-packs/packs')
  })

  it('reads the full den section, honoring overrides', () => {
    const s = parseDenSettings(DEN_YAML, ROOT)
    expect(s).toEqual({
      enabled: true,
      host: '0.0.0.0',
      port: 5175,
      token: 'den-secret',
      termEnabled: true,
      staticDir: '/srv/den/dist',
      packsDir: '/opt/rivetos/packages/den-packs/packs',
    })
  })

  it('falls back to the default port on out-of-range values', () => {
    const s = parseDenSettings('den:\n  enabled: true\n  port: 99999\n', ROOT)
    expect(s.port).toBe(5174)
  })
})

// ---------------------------------------------------------------------------
// buildDenEnvContent
// ---------------------------------------------------------------------------

describe('buildDenEnvContent', () => {
  it('marks the file as generated/config-managed and writes all values', () => {
    const content = buildDenEnvContent(parseDenSettings(DEN_YAML, ROOT))
    expect(content).toMatch(/^# .*GENERATED by `rivetos update`/)
    expect(content).toContain('RIVETOS_DEN_HOST=0.0.0.0\n')
    expect(content).toContain('RIVETOS_DEN_PORT=5175\n')
    expect(content).toContain('RIVETOS_DEN_TOKEN=den-secret\n')
    expect(content).toContain('RIVETOS_DEN_TERM=1\n')
    expect(content).toContain('RIVETOS_DEN_STATIC_DIR=/srv/den/dist\n')
    expect(content).toContain('RIVETOS_DEN_PACKS_DIR=/opt/rivetos/packages/den-packs/packs\n')
  })

  it('omits the token and terminal lines when unset (den-server fail-safe defaults)', () => {
    const content = buildDenEnvContent(parseDenSettings('den:\n  enabled: true\n', ROOT))
    expect(content).not.toContain('RIVETOS_DEN_TOKEN')
    expect(content).not.toContain('RIVETOS_DEN_TERM=')
    expect(content).toContain('RIVETOS_DEN_HOST=127.0.0.1\n')
  })
})

describe('denProbeHost', () => {
  it('probes loopback for wildcard binds, the bind host otherwise', () => {
    expect(denProbeHost('0.0.0.0')).toBe('127.0.0.1')
    expect(denProbeHost('::')).toBe('127.0.0.1')
    expect(denProbeHost('127.0.0.1')).toBe('127.0.0.1')
    expect(denProbeHost('192.0.2.10')).toBe('192.0.2.10')
  })
})

// ---------------------------------------------------------------------------
// deployDenRemote — control flow over mocked SSH
// ---------------------------------------------------------------------------

/** Wire sshExecQuiet to answer by command shape. */
function stubQuiet(opts: { configYaml: string; unitState?: string; healthz?: string }) {
  sshExecQuietMock.mockImplementation((_host: string, command: string) => {
    if (command.includes('config.yaml')) return opts.configYaml
    if (command.includes('is-active')) return opts.unitState ?? 'inactive'
    if (command.includes('/healthz')) return opts.healthz ?? '{"ok":true}'
    return ''
  })
}

describe('deployDenRemote', () => {
  it('skips quietly when den is disabled and no unit is running', async () => {
    stubQuiet({ configYaml: 'runtime:\n  workspace: /tmp\n', unitState: 'inactive' })

    const outcome = await deployDenRemote('192.0.2.10', 'node-a', 'rivet', true)

    expect(outcome).toBe('skipped')
    expect(sshExecMock).not.toHaveBeenCalled()
  })

  it('leaves an active unit alone (with a notice) when den is disabled — no surprise teardowns', async () => {
    stubQuiet({ configYaml: 'runtime:\n  workspace: /tmp\n', unitState: 'active' })

    const outcome = await deployDenRemote('192.0.2.10', 'node-a', 'rivet', true)

    expect(outcome).toBe('unmanaged-active')
    // Never stops/disables/restarts anything.
    expect(sshExecMock).not.toHaveBeenCalled()
  })

  it('deploys end-to-end when den.enabled: build, unit, env, pty rebuild, restart, healthz', async () => {
    sshExecMock.mockResolvedValue(undefined)
    stubQuiet({ configYaml: DEN_YAML })

    const outcome = await deployDenRemote('192.0.2.10', 'node-a', 'rivet', true)

    expect(outcome).toBe('deployed')
    const commands = sshExecMock.mock.calls.map((c) => c[1])
    expect(commands.some((c) => c.includes('nx run @rivetos/den-server:build'))).toBe(true)
    expect(
      commands.some((c) =>
        c.includes(
          'sudo cp /opt/rivetos/services/den-server/rivet-den.service /etc/systemd/system/rivet-den.service',
        ),
      ),
    ).toBe(true)
    expect(commands.some((c) => c.includes('systemctl enable rivet-den'))).toBe(true)
    expect(commands.some((c) => c.includes('npm rebuild node-pty'))).toBe(true)
    expect(commands.some((c) => c.includes("require('node-pty')"))).toBe(true)
    expect(commands.some((c) => c.includes('sudo systemctl restart rivet-den'))).toBe(true)

    // The generated den.env travels base64-encoded — decode and verify.
    const envCmd = commands.find((c) => c.includes('den.env'))
    expect(envCmd).toBeDefined()
    const b64 = /echo '([A-Za-z0-9+/=]+)'/.exec(envCmd!)?.[1]
    expect(b64).toBeDefined()
    const env = Buffer.from(b64!, 'base64').toString('utf-8')
    expect(env).toContain('RIVETOS_DEN_PORT=5175')
    expect(env).toContain('RIVETOS_DEN_TOKEN=den-secret')
    expect(env).toContain('RIVETOS_DEN_TERM=1')
    expect(envCmd).toContain('chmod 600 /home/rivet/.rivetos/den.env')
  })

  it('skips the node-pty rebuild when terminals are off', async () => {
    sshExecMock.mockResolvedValue(undefined)
    stubQuiet({ configYaml: 'den:\n  enabled: true\n' })

    const outcome = await deployDenRemote('192.0.2.10', 'node-a', 'rivet', true)

    expect(outcome).toBe('deployed')
    const commands = sshExecMock.mock.calls.map((c) => c[1])
    expect(commands.some((c) => c.includes('node-pty'))).toBe(false)
  })

  it('degrades to a warning when the node-pty rebuild fails (term 503s by design)', async () => {
    sshExecMock.mockImplementation((_host, command: string) => {
      if (command.includes('node-pty')) {
        return Promise.reject(new Error('gyp ERR! find Python'))
      }
      return Promise.resolve()
    })
    stubQuiet({ configYaml: DEN_YAML })

    const outcome = await deployDenRemote('192.0.2.10', 'node-a', 'rivet', true)

    expect(outcome).toBe('deployed')
    // Still restarted the service after the failed rebuild.
    const commands = sshExecMock.mock.calls.map((c) => c[1])
    expect(commands.some((c) => c.includes('systemctl restart rivet-den'))).toBe(true)
  })

  it('fails (without throwing) when the den build fails', async () => {
    sshExecMock.mockImplementation((_host, command: string) => {
      if (command.includes(':build')) return Promise.reject(new Error('tsc exploded'))
      return Promise.resolve()
    })
    stubQuiet({ configYaml: DEN_YAML })

    const outcome = await deployDenRemote('192.0.2.10', 'node-a', 'rivet', true)

    expect(outcome).toBe('failed')
    // Never got as far as touching the unit or restarting.
    const commands = sshExecMock.mock.calls.map((c) => c[1])
    expect(commands.some((c) => c.includes('systemctl restart rivet-den'))).toBe(false)
  })

  it('writes unit + env but skips restart and health probe with --no-restart', async () => {
    sshExecMock.mockResolvedValue(undefined)
    stubQuiet({ configYaml: DEN_YAML })

    const outcome = await deployDenRemote('192.0.2.10', 'node-a', 'rivet', false)

    expect(outcome).toBe('deployed')
    const commands = sshExecMock.mock.calls.map((c) => c[1])
    expect(commands.some((c) => c.includes('den.env'))).toBe(true)
    expect(commands.some((c) => c.includes('systemctl restart rivet-den'))).toBe(false)
    const quietCommands = sshExecQuietMock.mock.calls.map((c) => c[1])
    expect(quietCommands.some((c) => c.includes('/healthz'))).toBe(false)
  })

  it('drops the sudo prefix and chowns den.env for root logins', async () => {
    sshExecMock.mockResolvedValue(undefined)
    stubQuiet({ configYaml: DEN_YAML })

    const outcome = await deployDenRemote('192.0.2.10', 'node-a', 'root', true)

    expect(outcome).toBe('deployed')
    const commands = sshExecMock.mock.calls.map((c) => c[1])
    expect(commands.some((c) => c.includes('sudo '))).toBe(false)
    expect(commands.some((c) => c.includes('chown rivet:rivet /home/rivet/.rivetos/den.env'))).toBe(
      true,
    )
  })

  it('refuses a shell-unsafe den.host instead of interpolating it', async () => {
    stubQuiet({ configYaml: 'den:\n  enabled: true\n  host: "$(reboot)"\n' })

    const outcome = await deployDenRemote('192.0.2.10', 'node-a', 'rivet', true)

    expect(outcome).toBe('failed')
    expect(sshExecMock).not.toHaveBeenCalled()
  })
})
