/**
 * den-server deploy stage for `rivetos update`.
 *
 * When a node's ~/.rivetos/config.yaml has `den.enabled: true`, the update
 * manages rivet-den.service the same way it manages rivetos.service:
 *
 *   1. build services/den-server (workspace build — cache hit when the main
 *      build already covered it)
 *   2. install/refresh /etc/systemd/system/rivet-den.service from the repo's
 *      services/den-server/rivet-den.service
 *   3. GENERATE ~/.rivetos/den.env from the config's den: section (host/port/
 *      token/terminal flag/static+packs dirs) — the env file is config-managed,
 *      never hand-edited
 *   4. `npm rebuild node-pty` against /usr/bin/node when den.terminal.enabled
 *      (the ABI must match the unit's `ExecStart=/usr/bin/node`); a missing
 *      toolchain degrades to a warning — term endpoints answer 503 by design
 *   5. restart rivet-den.service and probe /healthz
 *
 * When den.enabled is false/absent but rivet-den.service is active, the
 * service is left alone with a notice — no surprise teardowns in v1.
 */

import { execSync } from 'node:child_process'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { parse as parseYaml } from 'yaml'
import { sshExec, sshExecQuiet, isSafeArg } from '../../lib/ssh.js'

/** Matches remote-nodes.ts — systemctl restart blocks until the unit is up. */
const DEN_RESTART_TIMEOUT_MS = 90_000
/** Total budget for the post-restart /healthz poll. */
const DEN_HEALTH_TIMEOUT_MS = 15_000
const DEN_HEALTH_INTERVAL_MS = 2_000

// ---------------------------------------------------------------------------
// Config → deploy settings
// ---------------------------------------------------------------------------

export interface DenDeploySettings {
  enabled: boolean
  host: string
  port: number
  token: string
  termEnabled: boolean
  staticDir: string
  packsDir: string
}

export type DenDeployOutcome = 'deployed' | 'skipped' | 'failed' | 'unmanaged-active'

/**
 * Extract the den: section from a raw config.yaml string and apply deploy
 * defaults. `root` is the install root the static/packs defaults derive from
 * (/opt/rivetos on managed nodes). Missing/unparseable config → disabled.
 *
 * Deliberately lenient: hard validation is the config validator's job
 * (packages/boot validateDen); the deploy stage just needs safe values.
 */
export function parseDenSettings(
  rawYaml: string | null | undefined,
  root: string,
): DenDeploySettings {
  const defaults: DenDeploySettings = {
    enabled: false,
    host: '127.0.0.1',
    port: 5174,
    token: '',
    termEnabled: false,
    staticDir: join(root, 'apps', 'den', 'dist'),
    packsDir: join(root, 'packages', 'den-packs', 'packs'),
  }

  if (!rawYaml) return defaults

  let parsed: unknown
  try {
    parsed = parseYaml(rawYaml)
  } catch {
    return defaults
  }
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return defaults

  const den = (parsed as Record<string, unknown>).den
  if (!den || typeof den !== 'object' || Array.isArray(den)) return defaults
  const d = den as Record<string, unknown>

  const terminal =
    d.terminal && typeof d.terminal === 'object' && !Array.isArray(d.terminal)
      ? (d.terminal as Record<string, unknown>)
      : undefined

  const port =
    typeof d.port === 'number' && Number.isInteger(d.port) && d.port >= 1 && d.port <= 65535
      ? d.port
      : defaults.port

  return {
    enabled: d.enabled === true,
    host: typeof d.host === 'string' && d.host.trim() !== '' ? d.host.trim() : defaults.host,
    port,
    token: typeof d.token === 'string' ? d.token : '',
    termEnabled: terminal?.enabled === true,
    staticDir:
      typeof d.static_dir === 'string' && d.static_dir.trim() !== ''
        ? d.static_dir.trim()
        : defaults.staticDir,
    packsDir:
      typeof d.packs_dir === 'string' && d.packs_dir.trim() !== ''
        ? d.packs_dir.trim()
        : defaults.packsDir,
  }
}

/**
 * Render ~/.rivetos/den.env from the den config section. The header makes the
 * ownership explicit: this file is generated, config.yaml is the source of
 * truth. (systemd EnvironmentFile takes values literally — no quoting needed
 * for these token-safe values.)
 */
export function buildDenEnvContent(s: DenDeploySettings): string {
  const lines = [
    '# ~/.rivetos/den.env — GENERATED by `rivetos update` from the den: section of',
    '# ~/.rivetos/config.yaml. Do not hand-edit: this file is rewritten on every',
    '# update. Change config.yaml and re-run `rivetos update` instead.',
    `RIVETOS_DEN_HOST=${s.host}`,
    `RIVETOS_DEN_PORT=${String(s.port)}`,
  ]
  if (s.token) lines.push(`RIVETOS_DEN_TOKEN=${s.token}`)
  if (s.termEnabled) lines.push('RIVETOS_DEN_TERM=1')
  lines.push(`RIVETOS_DEN_STATIC_DIR=${s.staticDir}`)
  lines.push(`RIVETOS_DEN_PACKS_DIR=${s.packsDir}`)
  return lines.join('\n') + '\n'
}

/** Host to curl for the health probe — wildcard binds answer on loopback. */
export function denProbeHost(bindHost: string): string {
  return bindHost === '0.0.0.0' || bindHost === '::' ? '127.0.0.1' : bindHost
}

function warnUnresolvedEnvRefs(tag: string, s: DenDeploySettings): void {
  // Boot's config loader resolves ${ENV_VAR} at runtime; den.env generation
  // does not (it can't know a remote node's env). Values are written literally.
  for (const [field, value] of [
    ['token', s.token],
    ['host', s.host],
  ] as const) {
    if (value.includes('${')) {
      console.warn(
        `    ${tag} ⚠️  den.${field} contains an unresolved \${...} reference — den.env is ` +
          `written literally. Use a literal value in the den: section (den.env is chmod 600).`,
      )
    }
  }
}

// ---------------------------------------------------------------------------
// Remote deploy (over SSH — mirrors remote-nodes.ts patterns)
// ---------------------------------------------------------------------------

/**
 * Deploy/refresh den-server on a remote node according to that node's own
 * config. Reads the remote ~/.rivetos/config.yaml, so per-node den settings
 * are honored without any central roster of den nodes.
 *
 * Never throws; failures are logged and reported via the outcome so a broken
 * den doesn't fail the node's rivetos update (den is auxiliary).
 */
export async function deployDenRemote(
  host: string,
  nodeName: string,
  sshUser: string,
  restart: boolean,
): Promise<DenDeployOutcome> {
  const tag = `[${nodeName}]`
  const sudo = sshUser === 'root' ? '' : 'sudo '

  // The unit runs as User=rivet with EnvironmentFile under /home/rivet, so
  // read/write the rivet user's ~/.rivetos regardless of the SSH login
  // (root-fallback nodes included). \$HOME escapes local expansion in
  // sshExecQuiet's double-quoted wrapper; the remote shell expands it.
  const rawConfig = sshExecQuiet(
    host,
    'cat /home/rivet/.rivetos/config.yaml 2>/dev/null || cat \\$HOME/.rivetos/config.yaml 2>/dev/null',
    sshUser,
  )
  const den = parseDenSettings(rawConfig || null, '/opt/rivetos')

  if (!den.enabled) {
    const state = sshExecQuiet(
      host,
      `${sudo}systemctl is-active rivet-den 2>/dev/null || true`,
      sshUser,
    )
    if (state === 'active') {
      console.log(
        `    ${tag} ℹ️  rivet-den.service is active but den.enabled is not set in config — ` +
          `left running (unmanaged). Add a den: section to manage it, or stop it manually.`,
      )
      return 'unmanaged-active'
    }
    return 'skipped'
  }

  // These values flow into remote shell commands — refuse anything unsafe.
  if (!isSafeArg(den.host)) {
    console.error(
      `    ${tag} ❌ den.host "${den.host}" contains shell-unsafe characters — skipping den deploy`,
    )
    return 'failed'
  }
  warnUnresolvedEnvRefs(tag, den)

  console.log(
    `    ${tag} Deploying den-server (port ${String(den.port)}${den.termEnabled ? ', terminals on' : ''})...`,
  )

  // Step 1: build den-server (usually an nx cache hit after the main build)
  try {
    await sshExec(
      host,
      'cd /opt/rivetos && npx nx run @rivetos/den-server:build',
      `${tag} den build`,
      120_000,
      sshUser,
    )
  } catch (err: unknown) {
    console.error(`    ${tag} ❌ den build failed: ${(err as Error).message}`)
    return 'failed'
  }

  // Step 2: install/refresh the systemd unit from the repo
  try {
    await sshExec(
      host,
      `${sudo}cp /opt/rivetos/services/den-server/rivet-den.service /etc/systemd/system/rivet-den.service && ` +
        `${sudo}systemctl daemon-reload && ${sudo}systemctl enable rivet-den`,
      `${tag} den unit install`,
      30_000,
      sshUser,
    )
  } catch (err: unknown) {
    console.error(`    ${tag} ❌ den unit install failed: ${(err as Error).message}`)
    return 'failed'
  }

  // Step 3: generate den.env (base64 transport dodges ssh quoting; chmod 600
  // because the token lives here; chown for root-fallback logins)
  try {
    const b64 = Buffer.from(buildDenEnvContent(den), 'utf-8').toString('base64')
    const chown = sshUser === 'root' ? ' && chown rivet:rivet /home/rivet/.rivetos/den.env' : ''
    await sshExec(
      host,
      `mkdir -p /home/rivet/.rivetos && echo '${b64}' | base64 -d > /home/rivet/.rivetos/den.env && ` +
        `chmod 600 /home/rivet/.rivetos/den.env${chown}`,
      `${tag} den.env`,
      15_000,
      sshUser,
    )
  } catch (err: unknown) {
    console.error(`    ${tag} ❌ den.env write failed: ${(err as Error).message}`)
    return 'failed'
  }

  // Step 4: node-pty rebuild against /usr/bin/node (the unit's ExecStart node).
  // Non-fatal: a missing toolchain means term endpoints 503 — by design.
  if (den.termEnabled) {
    try {
      await sshExec(
        host,
        'cd /opt/rivetos && PATH=/usr/bin:$PATH npm rebuild node-pty',
        `${tag} node-pty rebuild`,
        180_000,
        sshUser,
      )
      await sshExec(
        host,
        `cd /opt/rivetos && /usr/bin/node -e "require('node-pty').spawn('true',[],{});console.log('ok')"`,
        `${tag} node-pty verify`,
        15_000,
        sshUser,
      )
    } catch (err: unknown) {
      console.warn(
        `    ${tag} ⚠️  node-pty rebuild/verify failed (${(err as Error).message}) — terminals ` +
          `will answer 503 until fixed (see docs/DEN.md "node-pty ABI runbook")`,
      )
    }
  }

  // Step 5: restart + health probe
  if (!restart) {
    console.log(`    ${tag} ✅ den refreshed (unit + env written; restart skipped)`)
    return 'deployed'
  }
  try {
    await sshExec(
      host,
      `${sudo}systemctl restart rivet-den`,
      `${tag} den restart`,
      DEN_RESTART_TIMEOUT_MS,
      sshUser,
    )
  } catch (err: unknown) {
    console.error(`    ${tag} ❌ den restart failed: ${(err as Error).message}`)
    return 'failed'
  }

  const probe = `curl -fsS -m 3 http://${denProbeHost(den.host)}:${String(den.port)}/healthz`
  const deadline = Date.now() + DEN_HEALTH_TIMEOUT_MS
  for (;;) {
    const out = sshExecQuiet(host, probe, sshUser)
    if (out) {
      console.log(`    ${tag} ✅ den deployed — /healthz ok on :${String(den.port)}`)
      return 'deployed'
    }
    if (Date.now() >= deadline) break
    await new Promise((r) => setTimeout(r, DEN_HEALTH_INTERVAL_MS))
  }
  console.error(
    `    ${tag} ❌ den /healthz did not answer within ${String(DEN_HEALTH_TIMEOUT_MS / 1000)}s ` +
      `of restart — check: journalctl -u rivet-den`,
  )
  return 'failed'
}

/**
 * npm-mode nodes have no source checkout, so there is nothing to build or
 * copy the unit from — den deploy is git-mode only for now. This probe just
 * surfaces the gap loudly instead of silently skipping a den-enabled node.
 */
export function noteDenSkippedForNpmMode(host: string, nodeName: string, sshUser: string): void {
  const rawConfig = sshExecQuiet(
    host,
    'cat /home/rivet/.rivetos/config.yaml 2>/dev/null || cat \\$HOME/.rivetos/config.yaml 2>/dev/null',
    sshUser,
  )
  const den = parseDenSettings(rawConfig || null, '/opt/rivetos')
  if (den.enabled) {
    console.log(
      `    [${nodeName}] ⚠️  den.enabled is set but npm-mode updates can't deploy den-server yet ` +
        `(needs a source checkout) — skipped`,
    )
  }
}

// ---------------------------------------------------------------------------
// Local deploy (this node — mirrors the remote steps with local exec)
// ---------------------------------------------------------------------------

function execLocal(cmd: string, cwd: string, timeoutMs: number): void {
  execSync(cmd, {
    cwd,
    encoding: 'utf-8',
    timeout: timeoutMs,
    env: { ...process.env, HOME: process.env.HOME ?? '/root' },
    stdio: ['pipe', 'pipe', 'pipe'],
  })
}

function execLocalQuiet(cmd: string): string {
  try {
    return execSync(cmd, {
      encoding: 'utf-8',
      timeout: 15_000,
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim()
  } catch {
    return ''
  }
}

/** First readable ~/.rivetos/config.yaml among the candidate home dirs. */
async function readLocalConfig(homes: string[]): Promise<string | null> {
  for (const home of homes) {
    try {
      return await readFile(join(home, '.rivetos', 'config.yaml'), 'utf-8')
    } catch {
      // try next
    }
  }
  return null
}

/**
 * Deploy/refresh den-server on the local node according to ~/.rivetos/config.yaml.
 * Same contract as deployDenRemote: never throws, logs its own outcome.
 */
export async function deployDenLocal(root: string, restart: boolean): Promise<DenDeployOutcome> {
  const tag = '[local]'
  const sudo = typeof process.getuid === 'function' && process.getuid() === 0 ? '' : 'sudo '

  // The unit runs as User=rivet — prefer the rivet user's home for both the
  // config read and the den.env write, falling back to $HOME (dev installs).
  const rivetHome = existsSync('/home/rivet') ? '/home/rivet' : (process.env.HOME ?? '/root')

  const rawConfig = await readLocalConfig([rivetHome, process.env.HOME ?? '/root'])
  const den = parseDenSettings(rawConfig, root)

  if (!den.enabled) {
    const state = execLocalQuiet('systemctl is-active rivet-den 2>/dev/null || true')
    if (state === 'active') {
      console.log(
        `    ${tag} ℹ️  rivet-den.service is active but den.enabled is not set in config — ` +
          `left running (unmanaged). Add a den: section to manage it, or stop it manually.`,
      )
      return 'unmanaged-active'
    }
    return 'skipped'
  }

  if (!isSafeArg(den.host)) {
    console.error(
      `    ${tag} ❌ den.host "${den.host}" contains shell-unsafe characters — skipping den deploy`,
    )
    return 'failed'
  }
  warnUnresolvedEnvRefs(tag, den)

  console.log(
    `    ${tag} Deploying den-server (port ${String(den.port)}${den.termEnabled ? ', terminals on' : ''})...`,
  )

  try {
    execLocal('npx nx run @rivetos/den-server:build', root, 120_000)
  } catch (err: unknown) {
    console.error(`    ${tag} ❌ den build failed: ${(err as Error).message}`)
    return 'failed'
  }

  try {
    execLocal(
      `${sudo}cp ${root}/services/den-server/rivet-den.service /etc/systemd/system/rivet-den.service && ` +
        `${sudo}systemctl daemon-reload && ${sudo}systemctl enable rivet-den`,
      root,
      30_000,
    )
  } catch (err: unknown) {
    console.error(`    ${tag} ❌ den unit install failed: ${(err as Error).message}`)
    return 'failed'
  }

  try {
    const envDir = join(rivetHome, '.rivetos')
    mkdirSync(envDir, { recursive: true })
    writeFileSync(join(envDir, 'den.env'), buildDenEnvContent(den), { mode: 0o600 })
    if (sudo === '') {
      // Running as root — hand the file to the service user.
      execLocalQuiet(`chown rivet:rivet ${join(envDir, 'den.env')} 2>/dev/null || true`)
    }
  } catch (err: unknown) {
    console.error(`    ${tag} ❌ den.env write failed: ${(err as Error).message}`)
    return 'failed'
  }

  if (den.termEnabled) {
    try {
      execLocal('PATH=/usr/bin:$PATH npm rebuild node-pty', root, 180_000)
      execLocal(
        `/usr/bin/node -e "require('node-pty').spawn('true',[],{});console.log('ok')"`,
        root,
        15_000,
      )
    } catch (err: unknown) {
      console.warn(
        `    ${tag} ⚠️  node-pty rebuild/verify failed (${(err as Error).message}) — terminals ` +
          `will answer 503 until fixed (see docs/DEN.md "node-pty ABI runbook")`,
      )
    }
  }

  if (!restart) {
    console.log(`    ${tag} ✅ den refreshed (unit + env written; restart skipped)`)
    return 'deployed'
  }

  try {
    execLocal(`${sudo}systemctl restart rivet-den`, root, DEN_RESTART_TIMEOUT_MS)
  } catch (err: unknown) {
    console.error(`    ${tag} ❌ den restart failed: ${(err as Error).message}`)
    return 'failed'
  }

  const probe = `curl -fsS -m 3 http://${denProbeHost(den.host)}:${String(den.port)}/healthz`
  const deadline = Date.now() + DEN_HEALTH_TIMEOUT_MS
  for (;;) {
    if (execLocalQuiet(probe)) {
      console.log(`    ${tag} ✅ den deployed — /healthz ok on :${String(den.port)}`)
      return 'deployed'
    }
    if (Date.now() >= deadline) break
    await new Promise((r) => setTimeout(r, DEN_HEALTH_INTERVAL_MS))
  }
  console.error(
    `    ${tag} ❌ den /healthz did not answer within ${String(DEN_HEALTH_TIMEOUT_MS / 1000)}s ` +
      `of restart — check: journalctl -u rivet-den`,
  )
  return 'failed'
}
