// https://developer.android.com/jetpack/compose/performance/stability/fix#configuration-file

// Kotlin Immutable Collections
kotlinx.collections.immutable.*

kotlin.uuid.*
kotlin.time.*

// Java Time
java.time.*

dev.rivet.app.data.model.Conversation
dev.rivet.app.data.model.MessageNode
dev.rivet.ai.ui.UIMessage
dev.rivet.ai.ui.UIMessageChoice
dev.rivet.ai.ui.MessageChunk
dev.rivet.ai.ui.UIMessageAnnotation
dev.rivet.ai.ui.ToolApprovalState
dev.rivet.ai.core.TokenUsage